#!/bin/bash

WD=`pwd`

cd ../flexc++ 
    build manual || exit 1
    build man || exit 1
cd $WD

yodl2html index.yo || exit 1

scp ../flexc++/tmp/man*/*.html index.html \
    fbb,flexcpp@web.sourceforge.net:htdocs/

echo -n "update the images as well [y/n] ? "
read yesno

if [ "$yesno" == "y" ] ; then
    scp -r ../flexc++/tmp/manual/images \
    fbb,flexcpp@web.sourceforge.net:htdocs/
fi

rm index.html

cd ../flexc++ 
    build distclean
