#!/bin/bash

WD=`pwd`

cd ../flexc++ 
    build manual || exit 1
    build man || exit 1
cd $WD

yodl2html index.yo || exit 1

scp ../flexc++/tmp/man*/*.html index.html \
    fbb,flexcpp@web.sourceforge.net:htdocs/

rm index.html

cd ../flexc++ 
    build distclean
