#!/bin/bash
PROJECT=flexc++

cd ~/git/${PROJECT}/src

                                        # load the version
VERSION=`grep VERSION ${PROJECT}/VERSION |
    sed 's/#define[[:space:]]\+VERSION[[:space:]]\+"\([^"]*\).*/\1/'`

DISTRIBUTION=${PROJECT}-${VERSION}      # define the distribution's dir name

tgz()
{
    ln -s ${PROJECT} ${DISTRIBUTION}        # distribution's dir name

    tar czvf $1 --exclude-from=excluded  ${DISTRIBUTION}/*

    rm ${DISTRIBUTION}                      # rm the link
}

case "$1" in 
    (d)
        tgz ../tarballs/${PROJECT}_${VERSION}.orig.tar.gz
    ;;

    (l|o)
        tgz ${PROJECT}_${VERSION}.tar.gz

        if [ "$1" == "o" ]
        then
            scp ${PROJECT}_${VERSION}.tar.gz \
          oosix:git/${PROJECT}/tarballs/${PROJECT}_${VERSION}.orig.tar.gz
            rm ${PROJECT}_${VERSION}.tar.gz
        fi
    ;;

    (*)
        echo "
Provide arg:
    d (debian)  to create a local .orig.tar.gz archive in 
                ../tarballs
    l (local)   to create ${PROJECT}_${VERSION}.tar.gz in this directory
    o (oosix)   same as 'l', but upload to oosix (IUO)
"
    exit 1
    ;;

esac

