// Generated by Bisonc++ V2.09.04 on Sat, 21 Jan 2012 16:07:34 +0100

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them

// $insert debugincludes
#include <iostream>
#include <sstream>
#include <string>
#include <map>
#include <iomanip>

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {288, 3}, // 1: input ->  opt_directives section_delimiter rules
     {290, 1}, // 2: section_delimiter (SECTION_DELIMITER) ->  SECTION_DELIMITER
     {289, 2}, // 3: opt_directives ->  opt_directives directive_line
     {289, 0}, // 4: opt_directives ->  <empty>
     {292, 2}, // 5: directive_line ('\x0a') ->  directive '\x0a'
     {293, 1}, // 6: directive ->  option
     {293, 1}, // 7: directive ->  start_condition_directive
     {293, 1}, // 8: directive ->  name_definition
     {293, 1}, // 9: directive (_error_) ->  _error_
     {293, 0}, // 10: directive ->  <empty>
     {295, 2}, // 11: start_condition_directive ->  start_condition_type start_condition_names
     {297, 2}, // 12: start_condition_type (INCL_START_CONDITION) ->  INCL_START_CONDITION start_condition_name_m
     {297, 2}, // 13: start_condition_type (EXCL_START_CONDITION) ->  EXCL_START_CONDITION start_condition_name_m
     {298, 2}, // 14: start_condition_names ->  start_condition_names identifier
     {298, 1}, // 15: start_condition_names ->  identifier
     {296, 2}, // 16: name_definition (STRING) ->  name_def STRING
     {301, 1}, // 17: name_def ->  identifier
     {294, 3}, // 18: option ('=') ->  inputinterface_m '=' stringOrIdent
     {294, 3}, // 19: option ('=') ->  inputimplementation_m '=' stringOrIdent
     {294, 3}, // 20: option ('=') ->  classname_m '=' stringOrIdent
     {294, 3}, // 21: option ('=') ->  lexfunctionname_m '=' stringOrIdent
     {294, 3}, // 22: option ('=') ->  baseclassheader_m '=' stringOrIdent
     {294, 3}, // 23: option ('=') ->  classheader_m '=' stringOrIdent
     {294, 3}, // 24: option ('=') ->  implementationheader_m '=' stringOrIdent
     {294, 3}, // 25: option ('=') ->  lexsource_m '=' stringOrIdent
     {294, 3}, // 26: option ('=') ->  skeleton_directory_m '=' stringOrIdent
     {294, 3}, // 27: option ('=') ->  namespace_m '=' stringOrIdent
     {294, 1}, // 28: option (INTERACTIVE) ->  INTERACTIVE
     {294, 2}, // 29: option (DEBUG) ->  DEBUG opt_debugnamelist
     {294, 2}, // 30: option (DEBUG_STEPS) ->  DEBUG_STEPS opt_steprange
     {294, 1}, // 31: option (NOLINES) ->  NOLINES
     {303, 1}, // 32: stringOrIdent (STRING) ->  STRING
     {303, 1}, // 33: stringOrIdent (IDENTIFIER) ->  IDENTIFIER
     {313, 3}, // 34: opt_debugnamelist ('=') ->  debugnamelist_m '=' debugnamelist
     {313, 0}, // 35: opt_debugnamelist ->  <empty>
     {316, 3}, // 36: debugnamelist ->  debugnamelist opt_comma debugname
     {316, 1}, // 37: debugnamelist ->  debugname
     {317, 1}, // 38: opt_comma (',') ->  ','
     {317, 0}, // 39: opt_comma ->  <empty>
     {318, 1}, // 40: debugname (IDENTIFIER) ->  IDENTIFIER
     {314, 4}, // 41: opt_steprange ('=') ->  debugsteps_m '=' firststep opt_laststep
     {314, 0}, // 42: opt_steprange ->  <empty>
     {320, 1}, // 43: firststep (DECIMAL) ->  DECIMAL
     {321, 0}, // 44: opt_laststep ->  <empty>
     {321, 1}, // 45: opt_laststep (DECIMAL) ->  DECIMAL
     {291, 2}, // 46: rules ->  rules rule
     {291, 0}, // 47: rules ->  <empty>
     {323, 1}, // 48: block (BLOCK) ->  BLOCK
     {322, 2}, // 49: rule ('\x0a') ->  rule_def '\x0a'
     {324, 0}, // 50: rule_def ->  <empty>
     {324, 1}, // 51: rule_def (_error_) ->  _error_
     {324, 2}, // 52: rule_def (ERR) ->  ERR _error_
     {324, 1}, // 53: rule_def ->  regex_list
     {324, 2}, // 54: rule_def ->  regex_list block
     {324, 1}, // 55: rule_def ->  miniscanner_block
     {324, 1}, // 56: rule_def (EOF_PATTERN) ->  EOF_PATTERN
     {324, 2}, // 57: rule_def (EOF_PATTERN) ->  EOF_PATTERN block
     {325, 3}, // 58: regex_list (ORNL) ->  regex_list ORNL regex_list
     {325, 1}, // 59: regex_list ->  simple_regex
     {327, 2}, // 60: simple_regex ->  miniscanner basic_regex
     {327, 1}, // 61: simple_regex ->  basic_regex
     {330, 3}, // 62: basic_regex_list (ORNL) ->  basic_regex_list ORNL basic_regex_list
     {330, 1}, // 63: basic_regex_list ->  basic_regex
     {331, 2}, // 64: basic_rules ->  basic_rules basic_rule
     {331, 0}, // 65: basic_rules ->  <empty>
     {332, 2}, // 66: basic_rule ('\x0a') ->  basic_rule_def '\x0a'
     {333, 0}, // 67: basic_rule_def ->  <empty>
     {333, 1}, // 68: basic_rule_def ->  basic_regex_list
     {333, 2}, // 69: basic_rule_def ->  basic_regex_list block
     {333, 1}, // 70: basic_rule_def (EOF_PATTERN) ->  EOF_PATTERN
     {333, 2}, // 71: basic_rule_def (EOF_PATTERN) ->  EOF_PATTERN block
     {326, 5}, // 72: miniscanner_block ('{') ->  miniscanner '{' basic_rules basic_rule_def '}'
     {328, 3}, // 73: miniscanner ('<') ->  '<' miniscanner_specs '>'
     {334, 1}, // 74: miniscanner_specs ('*') ->  '*'
     {334, 1}, // 75: miniscanner_specs ->  miniscanner_list
     {335, 3}, // 76: miniscanner_list (',') ->  miniscanner_list ',' identifier
     {335, 1}, // 77: miniscanner_list ->  identifier
     {300, 1}, // 78: identifier (IDENTIFIER) ->  IDENTIFIER
     {329, 1}, // 79: basic_regex ->  p_regex
     {329, 3}, // 80: basic_regex ('/') ->  p_regex '/' p_regex
     {336, 1}, // 81: p_regex ->  regex
     {337, 1}, // 82: regex ->  combi_chars
     {337, 2}, // 83: regex (CHAR) ->  regex regex
     {337, 3}, // 84: regex ('|') ->  regex '|' regex
     {337, 3}, // 85: regex ('(') ->  '(' regex ')'
     {337, 2}, // 86: regex ->  regex quantifier
     {337, 1}, // 87: regex ->  characterclass
     {339, 1}, // 88: quantifier ('*') ->  '*'
     {339, 1}, // 89: quantifier ('+') ->  '+'
     {339, 1}, // 90: quantifier ('?') ->  '?'
     {339, 3}, // 91: quantifier ('{') ->  '{' interval '}'
     {341, 1}, // 92: interval ->  decimal
     {341, 3}, // 93: interval (',') ->  decimal ',' decimal
     {341, 2}, // 94: interval (',') ->  decimal ','
     {342, 1}, // 95: decimal (DECIMAL) ->  DECIMAL
     {340, 3}, // 96: characterclass (CC_PLUS) ->  characterclass CC_PLUS characterclass
     {340, 3}, // 97: characterclass (CC_MINUS) ->  characterclass CC_MINUS characterclass
     {340, 1}, // 98: characterclass ->  cc_set
     {343, 3}, // 99: cc_set ->  cc_start cc_contents cc_end
     {343, 3}, // 100: cc_set ->  cc_negated cc_contents cc_end
     {344, 2}, // 101: cc_start (CC_START) ->  CC_START cc_contents_m
     {347, 2}, // 102: cc_negated (CC_NEGATED) ->  CC_NEGATED cc_contents_m
     {346, 2}, // 103: cc_end (']') ->  ']' regex_block_m
     {345, 2}, // 104: cc_contents ->  cc_contents cc_element
     {345, 1}, // 105: cc_contents ->  cc_element
     {350, 1}, // 106: cc_element ->  combi_chars
     {350, 1}, // 107: cc_element (PREDEFINED_CLASS) ->  PREDEFINED_CLASS
     {350, 1}, // 108: cc_element ->  cc_char
     {351, 1}, // 109: cc_char ('/') ->  '/'
     {351, 1}, // 110: cc_char ('|') ->  '|'
     {351, 1}, // 111: cc_char ('(') ->  '('
     {351, 1}, // 112: cc_char (')') ->  ')'
     {351, 1}, // 113: cc_char ('*') ->  '*'
     {351, 1}, // 114: cc_char ('+') ->  '+'
     {351, 1}, // 115: cc_char ('?') ->  '?'
     {351, 1}, // 116: cc_char ('{') ->  '{'
     {351, 1}, // 117: cc_char ('}') ->  '}'
     {351, 1}, // 118: cc_char ('<') ->  '<'
     {351, 1}, // 119: cc_char ('>') ->  '>'
     {351, 1}, // 120: cc_char ('[') ->  '['
     {338, 1}, // 121: combi_chars (STRING) ->  STRING
     {338, 1}, // 122: combi_chars ->  decimal
     {338, 1}, // 123: combi_chars (ESCAPE_SEQUENCE) ->  ESCAPE_SEQUENCE
     {338, 1}, // 124: combi_chars ->  identifier
     {338, 1}, // 125: combi_chars (CHAR) ->  CHAR
     {338, 1}, // 126: combi_chars ('.') ->  '.'
     {338, 1}, // 127: combi_chars (',') ->  ','
     {338, 1}, // 128: combi_chars ('^') ->  '^'
     {338, 1}, // 129: combi_chars ('$') ->  '$'
     {338, 1}, // 130: combi_chars ('=') ->  '='
     {338, 1}, // 131: combi_chars ('-') ->  '-'
     {338, 1}, // 132: combi_chars (''') ->  '''
     {302, 1}, // 133: inputinterface_m (INPUTINTERFACE) ->  INPUTINTERFACE
     {304, 1}, // 134: inputimplementation_m (INPUTIMPLEMENTATION) ->  INPUTIMPLEMENTATION
     {305, 1}, // 135: classname_m (CLASSNAME) ->  CLASSNAME
     {306, 1}, // 136: lexfunctionname_m (LEXFUNCTIONNAME) ->  LEXFUNCTIONNAME
     {307, 1}, // 137: baseclassheader_m (BASECLASSHEADER) ->  BASECLASSHEADER
     {308, 1}, // 138: classheader_m (CLASSHEADER) ->  CLASSHEADER
     {309, 1}, // 139: implementationheader_m (IMPLEMENTATIONHEADER) ->  IMPLEMENTATIONHEADER
     {310, 1}, // 140: lexsource_m (LEXSOURCE) ->  LEXSOURCE
     {311, 1}, // 141: skeleton_directory_m (SKELETON_DIRECTORY) ->  SKELETON_DIRECTORY
     {312, 1}, // 142: namespace_m (NAMESPACE) ->  NAMESPACE
     {299, 0}, // 143: start_condition_name_m ->  <empty>
     {348, 0}, // 144: cc_contents_m ->  <empty>
     {349, 0}, // 145: regex_block_m ->  <empty>
     {315, 0}, // 146: debugnamelist_m ->  <empty>
     {319, 0}, // 147: debugsteps_m ->  <empty>
     {352, 1}, // 148: input_$ ->  input
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { DEF_RED}, {  3} },                  
    { {     288}, {  1} }, // input         
    { {     289}, {  2} }, // opt_directives
    { {       0}, { -4} },                  
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { ERR_REQ_DEF}, {  39} },                             
    { {         290}, {   3} }, // section_delimiter        
    { {         292}, {   4} }, // directive_line           
    { {         259}, {   5} }, // SECTION_DELIMITER        
    { {         293}, {   6} }, // directive                
    { {         294}, {   7} }, // option                   
    { {         295}, {   8} }, // start_condition_directive
    { {         296}, {   9} }, // name_definition          
    { {     _error_}, {  10} }, // _error_                  
    { {         302}, {  11} }, // inputinterface_m         
    { {         304}, {  12} }, // inputimplementation_m    
    { {         305}, {  13} }, // classname_m              
    { {         306}, {  14} }, // lexfunctionname_m        
    { {         307}, {  15} }, // baseclassheader_m        
    { {         308}, {  16} }, // classheader_m            
    { {         309}, {  17} }, // implementationheader_m   
    { {         310}, {  18} }, // lexsource_m              
    { {         311}, {  19} }, // skeleton_directory_m     
    { {         312}, {  20} }, // namespace_m              
    { {         268}, {  21} }, // INTERACTIVE              
    { {         263}, {  22} }, // DEBUG                    
    { {         264}, {  23} }, // DEBUG_STEPS              
    { {         272}, {  24} }, // NOLINES                  
    { {         297}, {  25} }, // start_condition_type     
    { {         301}, {  26} }, // name_def                 
    { {         267}, {  27} }, // INPUTINTERFACE           
    { {         266}, {  28} }, // INPUTIMPLEMENTATION      
    { {         262}, {  29} }, // CLASSNAME                
    { {         269}, {  30} }, // LEXFUNCTIONNAME          
    { {         260}, {  31} }, // BASECLASSHEADER          
    { {         261}, {  32} }, // CLASSHEADER              
    { {         265}, {  33} }, // IMPLEMENTATIONHEADER     
    { {         270}, {  34} }, // LEXSOURCE                
    { {         273}, {  35} }, // SKELETON_DIRECTORY       
    { {         271}, {  36} }, // NAMESPACE                
    { {         258}, {  37} }, // INCL_START_CONDITION     
    { {         257}, {  38} }, // EXCL_START_CONDITION     
    { {         300}, {  39} }, // identifier               
    { {         276}, {  40} }, // IDENTIFIER               
    { {           0}, { -10} },                             
};

SR__ s_3[] =
{
    { { DEF_RED}, {   2} },         
    { {     291}, {  41} }, // rules
    { {       0}, { -47} },         
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {        10}, { 42} }, // '\x0a'
    { {         0}, {  0} },          
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 43} }, // '='
    { {         0}, {  0} },       
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 44} }, // '='
    { {         0}, {  0} },       
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 45} }, // '='
    { {         0}, {  0} },       
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 46} }, // '='
    { {         0}, {  0} },       
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 47} }, // '='
    { {         0}, {  0} },       
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 48} }, // '='
    { {         0}, {  0} },       
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 49} }, // '='
    { {         0}, {  0} },       
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 50} }, // '='
    { {         0}, {  0} },       
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 51} }, // '='
    { {         0}, {  0} },       
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 52} }, // '='
    { {         0}, {  0} },       
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_22[] =
{
    { { REQ_DEF}, {    4} },                     
    { {     313}, {   53} }, // opt_debugnamelist
    { {     315}, {   54} }, // debugnamelist_m  
    { {      10}, {  -35} }, // '\x0a'           
    { {       0}, { -146} },                     
};

SR__ s_23[] =
{
    { { REQ_DEF}, {    4} },                 
    { {     314}, {   55} }, // opt_steprange
    { {     319}, {   56} }, // debugsteps_m 
    { {      10}, {  -42} }, // '\x0a'       
    { {       0}, { -147} },                 
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  4} },                         
    { {       298}, { 57} }, // start_condition_names
    { {       300}, { 58} }, // identifier           
    { {       276}, { 40} }, // IDENTIFIER           
    { {         0}, {  0} },                         
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       278}, { 59} }, // STRING
    { {         0}, {  0} },          
};

SR__ s_27[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -133} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -134} }, 
};

SR__ s_29[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -135} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -136} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -137} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -138} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -139} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -140} }, 
};

SR__ s_35[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -141} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -142} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {    2} },                          
    { {     299}, {   60} }, // start_condition_name_m
    { {       0}, { -143} },                          
};

SR__ s_38[] =
{
    { { DEF_RED}, {    2} },                          
    { {     299}, {   61} }, // start_condition_name_m
    { {       0}, { -143} },                          
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -78} }, 
};

SR__ s_41[] =
{
    { { ERR_REQ_DEF}, {  37} },                     
    { {         322}, {  62} }, // rule             
    { {         324}, {  63} }, // rule_def         
    { {     _error_}, {  64} }, // _error_          
    { {         274}, {  65} }, // ERR              
    { {         325}, {  66} }, // regex_list       
    { {         326}, {  67} }, // miniscanner_block
    { {         277}, {  68} }, // EOF_PATTERN      
    { {         327}, {  69} }, // simple_regex     
    { {         328}, {  70} }, // miniscanner      
    { {         329}, {  71} }, // basic_regex      
    { {          60}, {  72} }, // '<'              
    { {         336}, {  73} }, // p_regex          
    { {         337}, {  74} }, // regex            
    { {         338}, {  75} }, // combi_chars      
    { {          40}, {  76} }, // '('              
    { {         340}, {  77} }, // characterclass   
    { {         278}, {  78} }, // STRING           
    { {         342}, {  79} }, // decimal          
    { {         280}, {  80} }, // ESCAPE_SEQUENCE  
    { {         300}, {  81} }, // identifier       
    { {         285}, {  82} }, // CHAR             
    { {          46}, {  83} }, // '.'              
    { {          44}, {  84} }, // ','              
    { {          94}, {  85} }, // '^'              
    { {          36}, {  86} }, // '$'              
    { {          61}, {  87} }, // '='              
    { {          45}, {  88} }, // '-'              
    { {          39}, {  89} }, // '''              
    { {         343}, {  90} }, // cc_set           
    { {         279}, {  91} }, // DECIMAL          
    { {         276}, {  40} }, // IDENTIFIER       
    { {         344}, {  92} }, // cc_start         
    { {         347}, {  93} }, // cc_negated       
    { {         281}, {  94} }, // CC_START         
    { {         282}, {  95} }, // CC_NEGATED       
    { {       _EOF_}, {  -1} }, // _EOF_            
    { {           0}, { -50} },                     
};

SR__ s_42[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  4} },                 
    { {       303}, { 96} }, // stringOrIdent
    { {       278}, { 97} }, // STRING       
    { {       276}, { 98} }, // IDENTIFIER   
    { {         0}, {  0} },                 
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  4} },                 
    { {       303}, { 99} }, // stringOrIdent
    { {       278}, { 97} }, // STRING       
    { {       276}, { 98} }, // IDENTIFIER   
    { {         0}, {  0} },                 
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {   4} },                 
    { {       303}, { 100} }, // stringOrIdent
    { {       278}, {  97} }, // STRING       
    { {       276}, {  98} }, // IDENTIFIER   
    { {         0}, {   0} },                 
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {   4} },                 
    { {       303}, { 101} }, // stringOrIdent
    { {       278}, {  97} }, // STRING       
    { {       276}, {  98} }, // IDENTIFIER   
    { {         0}, {   0} },                 
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {   4} },                 
    { {       303}, { 102} }, // stringOrIdent
    { {       278}, {  97} }, // STRING       
    { {       276}, {  98} }, // IDENTIFIER   
    { {         0}, {   0} },                 
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {   4} },                 
    { {       303}, { 103} }, // stringOrIdent
    { {       278}, {  97} }, // STRING       
    { {       276}, {  98} }, // IDENTIFIER   
    { {         0}, {   0} },                 
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {   4} },                 
    { {       303}, { 104} }, // stringOrIdent
    { {       278}, {  97} }, // STRING       
    { {       276}, {  98} }, // IDENTIFIER   
    { {         0}, {   0} },                 
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {   4} },                 
    { {       303}, { 105} }, // stringOrIdent
    { {       278}, {  97} }, // STRING       
    { {       276}, {  98} }, // IDENTIFIER   
    { {         0}, {   0} },                 
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {   4} },                 
    { {       303}, { 106} }, // stringOrIdent
    { {       278}, {  97} }, // STRING       
    { {       276}, {  98} }, // IDENTIFIER   
    { {         0}, {   0} },                 
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {   4} },                 
    { {       303}, { 107} }, // stringOrIdent
    { {       278}, {  97} }, // STRING       
    { {       276}, {  98} }, // IDENTIFIER   
    { {         0}, {   0} },                 
};

SR__ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        61}, { 108} }, // '='
    { {         0}, {   0} },       
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        61}, { 109} }, // '='
    { {         0}, {   0} },       
};

SR__ s_57[] =
{
    { { REQ_DEF}, {   3} },              
    { {     300}, { 110} }, // identifier
    { {     276}, {  40} }, // IDENTIFIER
    { {       0}, { -11} },              
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 111} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_65[] =
{
    { { ERR_REQ}, {   2} },           
    { { _error_}, { 112} }, // _error_
    { {       0}, {   0} },           
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   4} },         
    { {     323}, { 113} }, // block
    { {     284}, { 114} }, // ORNL 
    { {     275}, { 115} }, // BLOCK
    { {       0}, { -53} },         
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   3} },         
    { {     323}, { 116} }, // block
    { {     275}, { 115} }, // BLOCK
    { {       0}, { -56} },         
};

SR__ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  27} },                   
    { {       123}, { 117} }, // '{'            
    { {       329}, { 118} }, // basic_regex    
    { {       336}, {  73} }, // p_regex        
    { {       337}, {  74} }, // regex          
    { {       338}, {  75} }, // combi_chars    
    { {        40}, {  76} }, // '('            
    { {       340}, {  77} }, // characterclass 
    { {       278}, {  78} }, // STRING         
    { {       342}, {  79} }, // decimal        
    { {       280}, {  80} }, // ESCAPE_SEQUENCE
    { {       300}, {  81} }, // identifier     
    { {       285}, {  82} }, // CHAR           
    { {        46}, {  83} }, // '.'            
    { {        44}, {  84} }, // ','            
    { {        94}, {  85} }, // '^'            
    { {        36}, {  86} }, // '$'            
    { {        61}, {  87} }, // '='            
    { {        45}, {  88} }, // '-'            
    { {        39}, {  89} }, // '''            
    { {       343}, {  90} }, // cc_set         
    { {       279}, {  91} }, // DECIMAL        
    { {       276}, {  40} }, // IDENTIFIER     
    { {       344}, {  92} }, // cc_start       
    { {       347}, {  93} }, // cc_negated     
    { {       281}, {  94} }, // CC_START       
    { {       282}, {  95} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, {   6} },                     
    { {       334}, { 119} }, // miniscanner_specs
    { {        42}, { 120} }, // '*'              
    { {       335}, { 121} }, // miniscanner_list 
    { {       300}, { 122} }, // identifier       
    { {       276}, {  40} }, // IDENTIFIER       
    { {         0}, {   0} },                     
};

SR__ s_73[] =
{
    { { REQ_DEF}, {   2} },       
    { {      47}, { 123} }, // '/'
    { {       0}, { -79} },       
};

SR__ s_74[] =
{
    { { REQ_DEF}, {  30} },                   
    { {     337}, { 124} }, // regex          
    { {     124}, { 125} }, // '|'            
    { {     339}, { 126} }, // quantifier     
    { {     338}, {  75} }, // combi_chars    
    { {      40}, {  76} }, // '('            
    { {     340}, {  77} }, // characterclass 
    { {      42}, { 127} }, // '*'            
    { {      43}, { 128} }, // '+'            
    { {      63}, { 129} }, // '?'            
    { {     123}, { 130} }, // '{'            
    { {     278}, {  78} }, // STRING         
    { {     342}, {  79} }, // decimal        
    { {     280}, {  80} }, // ESCAPE_SEQUENCE
    { {     300}, {  81} }, // identifier     
    { {     285}, {  82} }, // CHAR           
    { {      46}, {  83} }, // '.'            
    { {      44}, {  84} }, // ','            
    { {      94}, {  85} }, // '^'            
    { {      36}, {  86} }, // '$'            
    { {      61}, {  87} }, // '='            
    { {      45}, {  88} }, // '-'            
    { {      39}, {  89} }, // '''            
    { {     343}, {  90} }, // cc_set         
    { {     279}, {  91} }, // DECIMAL        
    { {     276}, {  40} }, // IDENTIFIER     
    { {     344}, {  92} }, // cc_start       
    { {     347}, {  93} }, // cc_negated     
    { {     281}, {  94} }, // CC_START       
    { {     282}, {  95} }, // CC_NEGATED     
    { {       0}, { -81} },                   
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -82} }, 
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  24} },                   
    { {       337}, { 131} }, // regex          
    { {       338}, {  75} }, // combi_chars    
    { {        40}, {  76} }, // '('            
    { {       340}, {  77} }, // characterclass 
    { {       278}, {  78} }, // STRING         
    { {       342}, {  79} }, // decimal        
    { {       280}, {  80} }, // ESCAPE_SEQUENCE
    { {       300}, {  81} }, // identifier     
    { {       285}, {  82} }, // CHAR           
    { {        46}, {  83} }, // '.'            
    { {        44}, {  84} }, // ','            
    { {        94}, {  85} }, // '^'            
    { {        36}, {  86} }, // '$'            
    { {        61}, {  87} }, // '='            
    { {        45}, {  88} }, // '-'            
    { {        39}, {  89} }, // '''            
    { {       343}, {  90} }, // cc_set         
    { {       279}, {  91} }, // DECIMAL        
    { {       276}, {  40} }, // IDENTIFIER     
    { {       344}, {  92} }, // cc_start       
    { {       347}, {  93} }, // cc_negated     
    { {       281}, {  94} }, // CC_START       
    { {       282}, {  95} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_77[] =
{
    { { REQ_DEF}, {   3} },            
    { {     286}, { 132} }, // CC_PLUS 
    { {     287}, { 133} }, // CC_MINUS
    { {       0}, { -87} },            
};

SR__ s_78[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -121} }, 
};

SR__ s_79[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -122} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -123} }, 
};

SR__ s_81[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -124} }, 
};

SR__ s_82[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -125} }, 
};

SR__ s_83[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -126} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -127} }, 
};

SR__ s_85[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -128} }, 
};

SR__ s_86[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -129} }, 
};

SR__ s_87[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -130} }, 
};

SR__ s_88[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -131} }, 
};

SR__ s_89[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -132} }, 
};

SR__ s_90[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -98} }, 
};

SR__ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -95} }, 
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {  32} },                    
    { {       345}, { 134} }, // cc_contents     
    { {       350}, { 135} }, // cc_element      
    { {       338}, { 136} }, // combi_chars     
    { {       283}, { 137} }, // PREDEFINED_CLASS
    { {       351}, { 138} }, // cc_char         
    { {       278}, {  78} }, // STRING          
    { {       342}, {  79} }, // decimal         
    { {       280}, {  80} }, // ESCAPE_SEQUENCE 
    { {       300}, {  81} }, // identifier      
    { {       285}, {  82} }, // CHAR            
    { {        46}, {  83} }, // '.'             
    { {        44}, {  84} }, // ','             
    { {        94}, {  85} }, // '^'             
    { {        36}, {  86} }, // '$'             
    { {        61}, {  87} }, // '='             
    { {        45}, {  88} }, // '-'             
    { {        39}, {  89} }, // '''             
    { {        47}, { 139} }, // '/'             
    { {       124}, { 140} }, // '|'             
    { {        40}, { 141} }, // '('             
    { {        41}, { 142} }, // ')'             
    { {        42}, { 143} }, // '*'             
    { {        43}, { 144} }, // '+'             
    { {        63}, { 145} }, // '?'             
    { {       123}, { 146} }, // '{'             
    { {       125}, { 147} }, // '}'             
    { {        60}, { 148} }, // '<'             
    { {        62}, { 149} }, // '>'             
    { {        91}, { 150} }, // '['             
    { {       279}, {  91} }, // DECIMAL         
    { {       276}, {  40} }, // IDENTIFIER      
    { {         0}, {   0} },                    
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {  32} },                    
    { {       345}, { 151} }, // cc_contents     
    { {       350}, { 135} }, // cc_element      
    { {       338}, { 136} }, // combi_chars     
    { {       283}, { 137} }, // PREDEFINED_CLASS
    { {       351}, { 138} }, // cc_char         
    { {       278}, {  78} }, // STRING          
    { {       342}, {  79} }, // decimal         
    { {       280}, {  80} }, // ESCAPE_SEQUENCE 
    { {       300}, {  81} }, // identifier      
    { {       285}, {  82} }, // CHAR            
    { {        46}, {  83} }, // '.'             
    { {        44}, {  84} }, // ','             
    { {        94}, {  85} }, // '^'             
    { {        36}, {  86} }, // '$'             
    { {        61}, {  87} }, // '='             
    { {        45}, {  88} }, // '-'             
    { {        39}, {  89} }, // '''             
    { {        47}, { 139} }, // '/'             
    { {       124}, { 140} }, // '|'             
    { {        40}, { 141} }, // '('             
    { {        41}, { 142} }, // ')'             
    { {        42}, { 143} }, // '*'             
    { {        43}, { 144} }, // '+'             
    { {        63}, { 145} }, // '?'             
    { {       123}, { 146} }, // '{'             
    { {       125}, { 147} }, // '}'             
    { {        60}, { 148} }, // '<'             
    { {        62}, { 149} }, // '>'             
    { {        91}, { 150} }, // '['             
    { {       279}, {  91} }, // DECIMAL         
    { {       276}, {  40} }, // IDENTIFIER      
    { {         0}, {   0} },                    
};

SR__ s_94[] =
{
    { { DEF_RED}, {    2} },                 
    { {     348}, {  152} }, // cc_contents_m
    { {       0}, { -144} },                 
};

SR__ s_95[] =
{
    { { DEF_RED}, {    2} },                 
    { {     348}, {  153} }, // cc_contents_m
    { {       0}, { -144} },                 
};

SR__ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_99[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_100[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_101[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_102[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_104[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_107[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_108[] =
{
    { { REQ_TOKEN}, {   4} },                 
    { {       316}, { 154} }, // debugnamelist
    { {       318}, { 155} }, // debugname    
    { {       276}, { 156} }, // IDENTIFIER   
    { {         0}, {   0} },                 
};

SR__ s_109[] =
{
    { { REQ_TOKEN}, {   3} },             
    { {       320}, { 157} }, // firststep
    { {       279}, { 158} }, // DECIMAL  
    { {         0}, {   0} },             
};

SR__ s_110[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_111[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_112[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_113[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_114[] =
{
    { { REQ_TOKEN}, {  30} },                   
    { {       325}, { 159} }, // regex_list     
    { {       327}, {  69} }, // simple_regex   
    { {       328}, { 160} }, // miniscanner    
    { {       329}, {  71} }, // basic_regex    
    { {        60}, {  72} }, // '<'            
    { {       336}, {  73} }, // p_regex        
    { {       337}, {  74} }, // regex          
    { {       338}, {  75} }, // combi_chars    
    { {        40}, {  76} }, // '('            
    { {       340}, {  77} }, // characterclass 
    { {       278}, {  78} }, // STRING         
    { {       342}, {  79} }, // decimal        
    { {       280}, {  80} }, // ESCAPE_SEQUENCE
    { {       300}, {  81} }, // identifier     
    { {       285}, {  82} }, // CHAR           
    { {        46}, {  83} }, // '.'            
    { {        44}, {  84} }, // ','            
    { {        94}, {  85} }, // '^'            
    { {        36}, {  86} }, // '$'            
    { {        61}, {  87} }, // '='            
    { {        45}, {  88} }, // '-'            
    { {        39}, {  89} }, // '''            
    { {       343}, {  90} }, // cc_set         
    { {       279}, {  91} }, // DECIMAL        
    { {       276}, {  40} }, // IDENTIFIER     
    { {       344}, {  92} }, // cc_start       
    { {       347}, {  93} }, // cc_negated     
    { {       281}, {  94} }, // CC_START       
    { {       282}, {  95} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_115[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_116[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_117[] =
{
    { { DEF_RED}, {   2} },               
    { {     331}, { 161} }, // basic_rules
    { {       0}, { -65} },               
};

SR__ s_118[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_119[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        62}, { 162} }, // '>'
    { {         0}, {   0} },       
};

SR__ s_120[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -74} }, 
};

SR__ s_121[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, { 163} }, // ','
    { {       0}, { -75} },       
};

SR__ s_122[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -77} }, 
};

SR__ s_123[] =
{
    { { REQ_TOKEN}, {  25} },                   
    { {       336}, { 164} }, // p_regex        
    { {       337}, {  74} }, // regex          
    { {       338}, {  75} }, // combi_chars    
    { {        40}, {  76} }, // '('            
    { {       340}, {  77} }, // characterclass 
    { {       278}, {  78} }, // STRING         
    { {       342}, {  79} }, // decimal        
    { {       280}, {  80} }, // ESCAPE_SEQUENCE
    { {       300}, {  81} }, // identifier     
    { {       285}, {  82} }, // CHAR           
    { {        46}, {  83} }, // '.'            
    { {        44}, {  84} }, // ','            
    { {        94}, {  85} }, // '^'            
    { {        36}, {  86} }, // '$'            
    { {        61}, {  87} }, // '='            
    { {        45}, {  88} }, // '-'            
    { {        39}, {  89} }, // '''            
    { {       343}, {  90} }, // cc_set         
    { {       279}, {  91} }, // DECIMAL        
    { {       276}, {  40} }, // IDENTIFIER     
    { {       344}, {  92} }, // cc_start       
    { {       347}, {  93} }, // cc_negated     
    { {       281}, {  94} }, // CC_START       
    { {       282}, {  95} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_124[] =
{
    { { REQ_DEF}, {  10} },                  
    { {     337}, { 124} }, // regex         
    { {     339}, { 126} }, // quantifier    
    { {     338}, {  75} }, // combi_chars   
    { {     340}, {  77} }, // characterclass
    { {     342}, {  79} }, // decimal       
    { {     300}, {  81} }, // identifier    
    { {     343}, {  90} }, // cc_set        
    { {     344}, {  92} }, // cc_start      
    { {     347}, {  93} }, // cc_negated    
    { {       0}, { -83} },                  
};

SR__ s_125[] =
{
    { { REQ_TOKEN}, {  24} },                   
    { {       337}, { 165} }, // regex          
    { {       338}, {  75} }, // combi_chars    
    { {        40}, {  76} }, // '('            
    { {       340}, {  77} }, // characterclass 
    { {       278}, {  78} }, // STRING         
    { {       342}, {  79} }, // decimal        
    { {       280}, {  80} }, // ESCAPE_SEQUENCE
    { {       300}, {  81} }, // identifier     
    { {       285}, {  82} }, // CHAR           
    { {        46}, {  83} }, // '.'            
    { {        44}, {  84} }, // ','            
    { {        94}, {  85} }, // '^'            
    { {        36}, {  86} }, // '$'            
    { {        61}, {  87} }, // '='            
    { {        45}, {  88} }, // '-'            
    { {        39}, {  89} }, // '''            
    { {       343}, {  90} }, // cc_set         
    { {       279}, {  91} }, // DECIMAL        
    { {       276}, {  40} }, // IDENTIFIER     
    { {       344}, {  92} }, // cc_start       
    { {       347}, {  93} }, // cc_negated     
    { {       281}, {  94} }, // CC_START       
    { {       282}, {  95} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_126[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -86} }, 
};

SR__ s_127[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -88} }, 
};

SR__ s_128[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -89} }, 
};

SR__ s_129[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -90} }, 
};

SR__ s_130[] =
{
    { { REQ_TOKEN}, {   4} },            
    { {       341}, { 166} }, // interval
    { {       342}, { 167} }, // decimal 
    { {       279}, {  91} }, // DECIMAL 
    { {         0}, {   0} },            
};

SR__ s_131[] =
{
    { { REQ_TOKEN}, {  31} },                   
    { {        41}, { 168} }, // ')'            
    { {       337}, { 124} }, // regex          
    { {       124}, { 125} }, // '|'            
    { {       339}, { 126} }, // quantifier     
    { {       338}, {  75} }, // combi_chars    
    { {        40}, {  76} }, // '('            
    { {       340}, {  77} }, // characterclass 
    { {        42}, { 127} }, // '*'            
    { {        43}, { 128} }, // '+'            
    { {        63}, { 129} }, // '?'            
    { {       123}, { 130} }, // '{'            
    { {       278}, {  78} }, // STRING         
    { {       342}, {  79} }, // decimal        
    { {       280}, {  80} }, // ESCAPE_SEQUENCE
    { {       300}, {  81} }, // identifier     
    { {       285}, {  82} }, // CHAR           
    { {        46}, {  83} }, // '.'            
    { {        44}, {  84} }, // ','            
    { {        94}, {  85} }, // '^'            
    { {        36}, {  86} }, // '$'            
    { {        61}, {  87} }, // '='            
    { {        45}, {  88} }, // '-'            
    { {        39}, {  89} }, // '''            
    { {       343}, {  90} }, // cc_set         
    { {       279}, {  91} }, // DECIMAL        
    { {       276}, {  40} }, // IDENTIFIER     
    { {       344}, {  92} }, // cc_start       
    { {       347}, {  93} }, // cc_negated     
    { {       281}, {  94} }, // CC_START       
    { {       282}, {  95} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_132[] =
{
    { { REQ_TOKEN}, {   7} },                  
    { {       340}, { 169} }, // characterclass
    { {       343}, {  90} }, // cc_set        
    { {       344}, {  92} }, // cc_start      
    { {       347}, {  93} }, // cc_negated    
    { {       281}, {  94} }, // CC_START      
    { {       282}, {  95} }, // CC_NEGATED    
    { {         0}, {   0} },                  
};

SR__ s_133[] =
{
    { { REQ_TOKEN}, {   7} },                  
    { {       340}, { 170} }, // characterclass
    { {       343}, {  90} }, // cc_set        
    { {       344}, {  92} }, // cc_start      
    { {       347}, {  93} }, // cc_negated    
    { {       281}, {  94} }, // CC_START      
    { {       282}, {  95} }, // CC_NEGATED    
    { {         0}, {   0} },                  
};

SR__ s_134[] =
{
    { { REQ_TOKEN}, {  33} },                    
    { {       346}, { 171} }, // cc_end          
    { {       350}, { 172} }, // cc_element      
    { {        93}, { 173} }, // ']'             
    { {       338}, { 136} }, // combi_chars     
    { {       283}, { 137} }, // PREDEFINED_CLASS
    { {       351}, { 138} }, // cc_char         
    { {       278}, {  78} }, // STRING          
    { {       342}, {  79} }, // decimal         
    { {       280}, {  80} }, // ESCAPE_SEQUENCE 
    { {       300}, {  81} }, // identifier      
    { {       285}, {  82} }, // CHAR            
    { {        46}, {  83} }, // '.'             
    { {        44}, {  84} }, // ','             
    { {        94}, {  85} }, // '^'             
    { {        36}, {  86} }, // '$'             
    { {        61}, {  87} }, // '='             
    { {        45}, {  88} }, // '-'             
    { {        39}, {  89} }, // '''             
    { {        47}, { 139} }, // '/'             
    { {       124}, { 140} }, // '|'             
    { {        40}, { 141} }, // '('             
    { {        41}, { 142} }, // ')'             
    { {        42}, { 143} }, // '*'             
    { {        43}, { 144} }, // '+'             
    { {        63}, { 145} }, // '?'             
    { {       123}, { 146} }, // '{'             
    { {       125}, { 147} }, // '}'             
    { {        60}, { 148} }, // '<'             
    { {        62}, { 149} }, // '>'             
    { {        91}, { 150} }, // '['             
    { {       279}, {  91} }, // DECIMAL         
    { {       276}, {  40} }, // IDENTIFIER      
    { {         0}, {   0} },                    
};

SR__ s_135[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -105} }, 
};

SR__ s_136[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -106} }, 
};

SR__ s_137[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -107} }, 
};

SR__ s_138[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -108} }, 
};

SR__ s_139[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -109} }, 
};

SR__ s_140[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -110} }, 
};

SR__ s_141[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -111} }, 
};

SR__ s_142[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -112} }, 
};

SR__ s_143[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -113} }, 
};

SR__ s_144[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -114} }, 
};

SR__ s_145[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -115} }, 
};

SR__ s_146[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -116} }, 
};

SR__ s_147[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -117} }, 
};

SR__ s_148[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -118} }, 
};

SR__ s_149[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -119} }, 
};

SR__ s_150[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -120} }, 
};

SR__ s_151[] =
{
    { { REQ_TOKEN}, {  33} },                    
    { {       346}, { 174} }, // cc_end          
    { {       350}, { 172} }, // cc_element      
    { {        93}, { 173} }, // ']'             
    { {       338}, { 136} }, // combi_chars     
    { {       283}, { 137} }, // PREDEFINED_CLASS
    { {       351}, { 138} }, // cc_char         
    { {       278}, {  78} }, // STRING          
    { {       342}, {  79} }, // decimal         
    { {       280}, {  80} }, // ESCAPE_SEQUENCE 
    { {       300}, {  81} }, // identifier      
    { {       285}, {  82} }, // CHAR            
    { {        46}, {  83} }, // '.'             
    { {        44}, {  84} }, // ','             
    { {        94}, {  85} }, // '^'             
    { {        36}, {  86} }, // '$'             
    { {        61}, {  87} }, // '='             
    { {        45}, {  88} }, // '-'             
    { {        39}, {  89} }, // '''             
    { {        47}, { 139} }, // '/'             
    { {       124}, { 140} }, // '|'             
    { {        40}, { 141} }, // '('             
    { {        41}, { 142} }, // ')'             
    { {        42}, { 143} }, // '*'             
    { {        43}, { 144} }, // '+'             
    { {        63}, { 145} }, // '?'             
    { {       123}, { 146} }, // '{'             
    { {       125}, { 147} }, // '}'             
    { {        60}, { 148} }, // '<'             
    { {        62}, { 149} }, // '>'             
    { {        91}, { 150} }, // '['             
    { {       279}, {  91} }, // DECIMAL         
    { {       276}, {  40} }, // IDENTIFIER      
    { {         0}, {   0} },                    
};

SR__ s_152[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -101} }, 
};

SR__ s_153[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -102} }, 
};

SR__ s_154[] =
{
    { { REQ_DEF}, {   4} },             
    { {     317}, { 175} }, // opt_comma
    { {      44}, { 176} }, // ','      
    { {      10}, { -34} }, // '\x0a'   
    { {       0}, { -39} },             
};

SR__ s_155[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_156[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_157[] =
{
    { { REQ_DEF}, {   3} },                
    { {     321}, { 177} }, // opt_laststep
    { {     279}, { 178} }, // DECIMAL     
    { {       0}, { -44} },                
};

SR__ s_158[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_159[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_160[] =
{
    { { REQ_TOKEN}, {  26} },                   
    { {       329}, { 118} }, // basic_regex    
    { {       336}, {  73} }, // p_regex        
    { {       337}, {  74} }, // regex          
    { {       338}, {  75} }, // combi_chars    
    { {        40}, {  76} }, // '('            
    { {       340}, {  77} }, // characterclass 
    { {       278}, {  78} }, // STRING         
    { {       342}, {  79} }, // decimal        
    { {       280}, {  80} }, // ESCAPE_SEQUENCE
    { {       300}, {  81} }, // identifier     
    { {       285}, {  82} }, // CHAR           
    { {        46}, {  83} }, // '.'            
    { {        44}, {  84} }, // ','            
    { {        94}, {  85} }, // '^'            
    { {        36}, {  86} }, // '$'            
    { {        61}, {  87} }, // '='            
    { {        45}, {  88} }, // '-'            
    { {        39}, {  89} }, // '''            
    { {       343}, {  90} }, // cc_set         
    { {       279}, {  91} }, // DECIMAL        
    { {       276}, {  40} }, // IDENTIFIER     
    { {       344}, {  92} }, // cc_start       
    { {       347}, {  93} }, // cc_negated     
    { {       281}, {  94} }, // CC_START       
    { {       282}, {  95} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_161[] =
{
    { { REQ_DEF}, {  30} },                    
    { {     333}, { 179} }, // basic_rule_def  
    { {     332}, { 180} }, // basic_rule      
    { {     330}, { 181} }, // basic_regex_list
    { {     277}, { 182} }, // EOF_PATTERN     
    { {     329}, { 183} }, // basic_regex     
    { {     336}, {  73} }, // p_regex         
    { {     337}, {  74} }, // regex           
    { {     338}, {  75} }, // combi_chars     
    { {      40}, {  76} }, // '('             
    { {     340}, {  77} }, // characterclass  
    { {     278}, {  78} }, // STRING          
    { {     342}, {  79} }, // decimal         
    { {     280}, {  80} }, // ESCAPE_SEQUENCE 
    { {     300}, {  81} }, // identifier      
    { {     285}, {  82} }, // CHAR            
    { {      46}, {  83} }, // '.'             
    { {      44}, {  84} }, // ','             
    { {      94}, {  85} }, // '^'             
    { {      36}, {  86} }, // '$'             
    { {      61}, {  87} }, // '='             
    { {      45}, {  88} }, // '-'             
    { {      39}, {  89} }, // '''             
    { {     343}, {  90} }, // cc_set          
    { {     279}, {  91} }, // DECIMAL         
    { {     276}, {  40} }, // IDENTIFIER      
    { {     344}, {  92} }, // cc_start        
    { {     347}, {  93} }, // cc_negated      
    { {     281}, {  94} }, // CC_START        
    { {     282}, {  95} }, // CC_NEGATED      
    { {       0}, { -67} },                    
};

SR__ s_162[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -73} }, 
};

SR__ s_163[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       300}, { 184} }, // identifier
    { {       276}, {  40} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR__ s_164[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -80} }, 
};

SR__ s_165[] =
{
    { { REQ_DEF}, {  11} },                  
    { {     337}, { 124} }, // regex         
    { {     339}, { 126} }, // quantifier    
    { {     338}, {  75} }, // combi_chars   
    { {     340}, {  77} }, // characterclass
    { {     342}, {  79} }, // decimal       
    { {     300}, {  81} }, // identifier    
    { {     285}, {  82} }, // CHAR          
    { {     343}, {  90} }, // cc_set        
    { {     344}, {  92} }, // cc_start      
    { {     347}, {  93} }, // cc_negated    
    { {       0}, { -84} },                  
};

SR__ s_166[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       125}, { 185} }, // '}'
    { {         0}, {   0} },       
};

SR__ s_167[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, { 186} }, // ','
    { {       0}, { -92} },       
};

SR__ s_168[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -85} }, 
};

SR__ s_169[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -96} }, 
};

SR__ s_170[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -97} }, 
};

SR__ s_171[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -99} }, 
};

SR__ s_172[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -104} }, 
};

SR__ s_173[] =
{
    { { DEF_RED}, {    2} },                 
    { {     349}, {  187} }, // regex_block_m
    { {       0}, { -145} },                 
};

SR__ s_174[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -100} }, 
};

SR__ s_175[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       318}, { 188} }, // debugname 
    { {       276}, { 156} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR__ s_176[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_177[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_178[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_179[] =
{
    { { REQ_TOKEN}, {   3} },          
    { {       125}, { 189} }, // '}'   
    { {        10}, { 190} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_180[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -64} }, 
};

SR__ s_181[] =
{
    { { REQ_DEF}, {   4} },         
    { {     323}, { 191} }, // block
    { {     284}, { 192} }, // ORNL 
    { {     275}, { 115} }, // BLOCK
    { {       0}, { -68} },         
};

SR__ s_182[] =
{
    { { REQ_DEF}, {   3} },         
    { {     323}, { 193} }, // block
    { {     275}, { 115} }, // BLOCK
    { {       0}, { -70} },         
};

SR__ s_183[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_184[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -76} }, 
};

SR__ s_185[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -91} }, 
};

SR__ s_186[] =
{
    { { REQ_DEF}, {   3} },           
    { {     342}, { 194} }, // decimal
    { {     279}, {  91} }, // DECIMAL
    { {       0}, { -94} },           
};

SR__ s_187[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -103} }, 
};

SR__ s_188[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_189[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR__ s_190[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_191[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_192[] =
{
    { { REQ_TOKEN}, {  27} },                    
    { {       330}, { 195} }, // basic_regex_list
    { {       329}, { 183} }, // basic_regex     
    { {       336}, {  73} }, // p_regex         
    { {       337}, {  74} }, // regex           
    { {       338}, {  75} }, // combi_chars     
    { {        40}, {  76} }, // '('             
    { {       340}, {  77} }, // characterclass  
    { {       278}, {  78} }, // STRING          
    { {       342}, {  79} }, // decimal         
    { {       280}, {  80} }, // ESCAPE_SEQUENCE 
    { {       300}, {  81} }, // identifier      
    { {       285}, {  82} }, // CHAR            
    { {        46}, {  83} }, // '.'             
    { {        44}, {  84} }, // ','             
    { {        94}, {  85} }, // '^'             
    { {        36}, {  86} }, // '$'             
    { {        61}, {  87} }, // '='             
    { {        45}, {  88} }, // '-'             
    { {        39}, {  89} }, // '''             
    { {       343}, {  90} }, // cc_set          
    { {       279}, {  91} }, // DECIMAL         
    { {       276}, {  40} }, // IDENTIFIER      
    { {       344}, {  92} }, // cc_start        
    { {       347}, {  93} }, // cc_negated      
    { {       281}, {  94} }, // CC_START        
    { {       282}, {  95} }, // CC_NEGATED      
    { {         0}, {   0} },                    
};

SR__ s_193[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_194[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -93} }, 
};

SR__ s_195[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -62} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,  s_153,  s_154,  s_155,  s_156,  s_157,  s_158,  s_159,
  s_160,  s_161,  s_162,  s_163,  s_164,  s_165,  s_166,  s_167,  s_168,  s_169,
  s_170,  s_171,  s_172,  s_173,  s_174,  s_175,  s_176,  s_177,  s_178,  s_179,
  s_180,  s_181,  s_182,  s_183,  s_184,  s_185,  s_186,  s_187,  s_188,  s_189,
  s_190,  s_191,  s_192,  s_193,  s_194,  s_195,
};

typedef std::map<int, char const *> SMap;
typedef SMap::value_type SMapVal;

SMapVal s_symArr[] =
{
    SMapVal(-2, "_UNDETERMINED_"),  // predefined symbols
    SMapVal(-1, "_EOF_"),
    SMapVal(256, "_error_"),

    SMapVal(257, "EXCL_START_CONDITION"),
    SMapVal(258, "INCL_START_CONDITION"),
    SMapVal(259, "SECTION_DELIMITER"),
    SMapVal(260, "BASECLASSHEADER"),
    SMapVal(261, "CLASSHEADER"),
    SMapVal(262, "CLASSNAME"),
    SMapVal(263, "DEBUG"),
    SMapVal(264, "DEBUG_STEPS"),
    SMapVal(265, "IMPLEMENTATIONHEADER"),
    SMapVal(266, "INPUTIMPLEMENTATION"),
    SMapVal(267, "INPUTINTERFACE"),
    SMapVal(268, "INTERACTIVE"),
    SMapVal(269, "LEXFUNCTIONNAME"),
    SMapVal(270, "LEXSOURCE"),
    SMapVal(271, "NAMESPACE"),
    SMapVal(272, "NOLINES"),
    SMapVal(273, "SKELETON_DIRECTORY"),
    SMapVal(274, "ERR"),
    SMapVal(275, "BLOCK"),
    SMapVal(276, "IDENTIFIER"),
    SMapVal(277, "EOF_PATTERN"),
    SMapVal(278, "STRING"),
    SMapVal(279, "DECIMAL"),
    SMapVal(280, "ESCAPE_SEQUENCE"),
    SMapVal(281, "CC_START"),
    SMapVal(282, "CC_NEGATED"),
    SMapVal(283, "PREDEFINED_CLASS"),
    SMapVal(284, "ORNL"),
    SMapVal(285, "CHAR"),
    SMapVal(286, "CC_PLUS"),
    SMapVal(287, "CC_MINUS"),
    SMapVal(288, "input"),
    SMapVal(289, "opt_directives"),
    SMapVal(290, "section_delimiter"),
    SMapVal(291, "rules"),
    SMapVal(292, "directive_line"),
    SMapVal(293, "directive"),
    SMapVal(294, "option"),
    SMapVal(295, "start_condition_directive"),
    SMapVal(296, "name_definition"),
    SMapVal(297, "start_condition_type"),
    SMapVal(298, "start_condition_names"),
    SMapVal(299, "start_condition_name_m"),
    SMapVal(300, "identifier"),
    SMapVal(301, "name_def"),
    SMapVal(302, "inputinterface_m"),
    SMapVal(303, "stringOrIdent"),
    SMapVal(304, "inputimplementation_m"),
    SMapVal(305, "classname_m"),
    SMapVal(306, "lexfunctionname_m"),
    SMapVal(307, "baseclassheader_m"),
    SMapVal(308, "classheader_m"),
    SMapVal(309, "implementationheader_m"),
    SMapVal(310, "lexsource_m"),
    SMapVal(311, "skeleton_directory_m"),
    SMapVal(312, "namespace_m"),
    SMapVal(313, "opt_debugnamelist"),
    SMapVal(314, "opt_steprange"),
    SMapVal(315, "debugnamelist_m"),
    SMapVal(316, "debugnamelist"),
    SMapVal(317, "opt_comma"),
    SMapVal(318, "debugname"),
    SMapVal(319, "debugsteps_m"),
    SMapVal(320, "firststep"),
    SMapVal(321, "opt_laststep"),
    SMapVal(322, "rule"),
    SMapVal(323, "block"),
    SMapVal(324, "rule_def"),
    SMapVal(325, "regex_list"),
    SMapVal(326, "miniscanner_block"),
    SMapVal(327, "simple_regex"),
    SMapVal(328, "miniscanner"),
    SMapVal(329, "basic_regex"),
    SMapVal(330, "basic_regex_list"),
    SMapVal(331, "basic_rules"),
    SMapVal(332, "basic_rule"),
    SMapVal(333, "basic_rule_def"),
    SMapVal(334, "miniscanner_specs"),
    SMapVal(335, "miniscanner_list"),
    SMapVal(336, "p_regex"),
    SMapVal(337, "regex"),
    SMapVal(338, "combi_chars"),
    SMapVal(339, "quantifier"),
    SMapVal(340, "characterclass"),
    SMapVal(341, "interval"),
    SMapVal(342, "decimal"),
    SMapVal(343, "cc_set"),
    SMapVal(344, "cc_start"),
    SMapVal(345, "cc_contents"),
    SMapVal(346, "cc_end"),
    SMapVal(347, "cc_negated"),
    SMapVal(348, "cc_contents_m"),
    SMapVal(349, "regex_block_m"),
    SMapVal(350, "cc_element"),
    SMapVal(351, "cc_char"),
    SMapVal(352, "input_$"),
};

SMap s_symbol
(
    s_symArr, s_symArr + sizeof(s_symArr) / sizeof(SMapVal)
);

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(true),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}

// $insert debugfunctions

std::ostringstream ParserBase::s_out__;

std::ostream &ParserBase::dflush__(std::ostream &out)
{
    std::ostringstream &s_out__ = dynamic_cast<std::ostringstream &>(out);

    std::cout << "    " << s_out__.str() << std::flush;
    s_out__.clear();
    s_out__.str("");
    return out;
}

std::string ParserBase::stype__(char const *pre, STYPE__ const &semVal, char const *post) const
{
    return "";
}
std::string ParserBase::symbol__(int value) const
{
    using namespace std;
    ostringstream ostr;
    SMap::const_iterator it = s_symbol.find(value);
    if (it != s_symbol.end())
        ostr << "`" << it->second << "'";
    else if (isprint(value))
        ostr << "`" << static_cast<char>(value) << "' (" << value << ")";
    else
        ostr << "'\\x" << setfill('0') << hex << setw(2) << value << "'";
    return ostr.str();
}


void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert debug
    if (d_debug__)
        s_out__ <<   "push(state " << state << stype__(", semantic TOS = ", d_val__, ")") << ')' << "\n" << dflush__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    // $insert debug
    if (d_debug__)
        s_out__ <<  "pop(" << count << ") from stack having size " << (d_stackIdx__ + 1) << "\n" << dflush__;
    if (d_stackIdx__ < static_cast<int>(count))
    {
        // $insert debug
        if (d_debug__)
            s_out__ <<  "Terminating parse(): unrecoverable input error at token " << symbol__(d_token__) << "\n" << dflush__;
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert debug
    if (d_debug__)
        s_out__ <<  "pop(): next state: " << d_state__ << ", token: " << symbol__(d_token__) ;
    // $insert debug
    if (d_debug__)
        s_out__ <<  stype__("semantic: ", d_val__) << "\n" << dflush__;
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    // $insert debug
    if (d_debug__)
        s_out__ <<  "executeAction(): of rule " << production ;
    // $insert debug
    if (d_debug__)
        s_out__ <<   stype__(", semantic [TOS]: ", d_val__) << " ..." << "\n" << dflush__;
    switch (production)
    {
        // $insert actioncases
        
        case 2:
#line 76 "grammar"
        {
         
         }
        break;

        case 12:
#line 31 "inc/directives"
        {
         
         }
        break;

        case 13:
#line 37 "inc/directives"
        {
         
         }
        break;

        case 14:
#line 44 "inc/directives"
        {
         
         }
        break;

        case 15:
#line 49 "inc/directives"
        {
         
         }
        break;

        case 16:
#line 56 "inc/directives"
        {
         d_scanner.addDefinition(d_vsp__[-1], d_scanner.matched());
         }
        break;

        case 17:
#line 63 "inc/directives"
        {
         d_scanner.newDefinition(); 
         }
        break;

        case 18:
#line 3 "inc/options"
        {
         
         }
        break;

        case 19:
#line 8 "inc/options"
        {
         
         }
        break;

        case 20:
#line 13 "inc/options"
        {
         
         }
        break;

        case 21:
#line 18 "inc/options"
        {
         
         }
        break;

        case 22:
#line 23 "inc/options"
        {
         
         }
        break;

        case 23:
#line 28 "inc/options"
        {
         
         }
        break;

        case 24:
#line 33 "inc/options"
        {
         
         }
        break;

        case 25:
#line 38 "inc/options"
        {
         
         }
        break;

        case 26:
#line 43 "inc/options"
        {
         
         }
        break;

        case 27:
#line 48 "inc/options"
        {
         
         }
        break;

        case 28:
#line 53 "inc/options"
        {
         
         }
        break;

        case 31:
#line 62 "inc/options"
        {
         
         }
        break;

        case 35:
#line 76 "inc/options"
        {
         
         }
        break;

        case 40:
#line 95 "inc/options"
        {
         
         }
        break;

        case 42:
#line 103 "inc/options"
        {
         
         }
        break;

        case 43:
#line 110 "inc/options"
        {
         
         }
        break;

        case 45:
#line 119 "inc/options"
        {
         
         }
        break;

        case 48:
#line 11 "inc/rules"
        {
         block();
         }
        break;

        case 54:
#line 37 "inc/rules"
        { cout << "BLOCK\n"; }
        break;

        case 58:
#line 54 "inc/rules"
        {cout << "ORNL\n";}
        break;

        case 60:
#line 63 "inc/rules"
        {cout << "<MINI>RE\n";}
        break;

        case 73:
#line 103 "inc/rules"
        {cout << "MINI\n";}
        break;

        case 78:
#line 120 "inc/rules"
        {
         d_val__ = d_scanner.matched();
         }
        break;

        case 80:
#line 133 "inc/rules"
        {cout << "LA\n";}
        break;

        case 81:
#line 139 "inc/rules"
        {cout << "RE\n";}
        break;

        case 84:
#line 150 "inc/rules"
        { cout << "OR\n"; }
        break;

        case 86:
#line 155 "inc/rules"
        { cout << "QTY\n"; }
        break;

        case 87:
#line 158 "inc/rules"
        { cout << "CLASS\n"; }
        break;

        case 133:
#line 3 "inc/messages"
        {
         d_msg = "name of the file holding Input's interface";
         }
        break;

        case 134:
#line 10 "inc/messages"
        {
         d_msg = "name of the file holding Input's implementations";
         }
        break;

        case 135:
#line 17 "inc/messages"
        {
         d_msg = "class name";
         }
        break;

        case 136:
#line 24 "inc/messages"
        {
         d_msg = "name of the lex() function";
         }
        break;

        case 137:
#line 31 "inc/messages"
        {
         d_msg = "scanner base class header file name";
         }
        break;

        case 138:
#line 38 "inc/messages"
        {
         d_msg = "scanner class header file name";
         }
        break;

        case 139:
#line 45 "inc/messages"
        {
         d_msg = "implementation header file name";
         }
        break;

        case 140:
#line 52 "inc/messages"
        {
         d_msg = "source file name of the lex function";
         }
        break;

        case 141:
#line 59 "inc/messages"
        {
         d_msg = "directory name of the flexc++ skeleton files";
         }
        break;

        case 142:
#line 66 "inc/messages"
        {
         d_msg = "name of the namespace to use";
         }
        break;

        case 143:
#line 72 "inc/messages"
        {
         d_msg = "list of start condition names";
         }
        break;

        case 144:
#line 78 "inc/messages"
        {
         d_msg = "character class contents";
         }
        break;

        case 145:
#line 84 "inc/messages"
        {
         d_msg = "pattern or action block";
         }
        break;

        case 146:
#line 90 "inc/messages"
        {
         d_msg = "debug identifiers";
         }
        break;

        case 147:
#line 96 "inc/messages"
        {
         d_msg = "debug step range";
         }
        break;

    }
    // $insert debug
    if (d_debug__)
        s_out__ <<  "... action of rule " << production << " completed" ;
    // $insert debug
    if (d_debug__)
        s_out__ <<   stype__(", semantic: ", d_val__) << "\n" << dflush__;
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

    // $insert debug
    if (d_debug__)
        s_out__ <<  "reduce(): by rule " << (&pi - s_productionInfo) ;
    // $insert debug
    if (d_debug__)
        s_out__ <<  " to N-terminal " << symbol__(d_token__) << stype__(", semantic = ", d_val__) << "\n" << dflush__;
}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
        // $insert debug
        if (d_debug__)
            s_out__ <<  "nextToken(): popped " << symbol__(d_token__) << stype__(", semantic = ", d_val__) << "\n" << dflush__;
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
    // $insert debug
    if (d_debug__)
        s_out__ <<  "nextToken(): using " << symbol__(d_token__) << stype__(", semantic = ", d_val__) << "\n" << dflush__;
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
        // $insert debug
        if (d_debug__)
            s_out__ <<  "lookup(" << d_state__ << ", " << symbol__(d_token__) ;
        // $insert debug
        if (d_debug__)
            s_out__ <<  "): default reduction by rule " << -elementPtr->d_action << "\n" << dflush__;
            return elementPtr->d_action;                
        }
        // $insert debug
        if (d_debug__)
            s_out__ <<  "lookup(" << d_state__ << ", " << symbol__(d_token__) << "): Not " ;
        // $insert debug
        if (d_debug__)
            s_out__ <<  "found. " << (recovery ? "Continue" : "Start") << " error recovery."  << "\n" << dflush__;

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;

// $insert debuglookup
    if (d_debug__)
    {
        s_out__ <<  "lookup(" << d_state__ << ", " << symbol__(d_token__);

        if (action < 0)             // a reduction is found
            s_out__ << "): reduce by rule " << -action;
        else if (action == 0)
            s_out__ <<  "): ACCEPT";
        else 
            s_out__ <<  "): shift " << action << " (" << symbol__(d_token__) << 
                        " processed)";

        s_out__ << "\n" << dflush__;
    }

    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }

    // $insert debug
    if (d_debug__)
        s_out__ <<  "errorRecovery(): " << d_nErrors__ << " error(s) so far. State = " << top__() << "\n" << dflush__;

    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        // $insert debug
        if (d_debug__)
            s_out__ <<  "errorRecovery(): pop state " << top__() << "\n" << dflush__;
        pop__();
    }
    // $insert debug
    if (d_debug__)
        s_out__ <<  "errorRecovery(): state " << top__() << " is an ERROR state" << "\n" << dflush__;

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();
                // $insert debug
                if (d_debug__)
                    s_out__ <<  "errorRecovery() SHIFT state " << action ;
                // $insert debug
                if (d_debug__)
                    s_out__ <<  ", continue with " << symbol__(d_token__) << "\n" << dflush__;

                if (gotToken)
                {
                    // $insert debug
                    if (d_debug__)
                        s_out__ <<  "errorRecovery() COMPLETED: next state " ;
                    // $insert debug
                    if (d_debug__)
                        s_out__ <<  action << ", no token yet" << "\n" << dflush__;

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
                // $insert debug
                if (d_debug__)
                    s_out__ <<  "errorRecovery() REDUCE by rule " << -action ;
                // $insert debug
                if (d_debug__)
                    s_out__ <<  ", token = " << symbol__(d_token__) << "\n" << dflush__;
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    // $insert debug
    if (d_debug__)
        s_out__ <<  "parse(): Parsing starts" << "\n" << dflush__;
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        // $insert debug
        if (d_debug__)
            s_out__ <<  "==" << "\n" << dflush__;
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    // $insert debug
    if (d_debug__)
        s_out__ <<  "parse(): returns " << retValue << "\n" << dflush__;
    return retValue;
}

