#!/bin/bash

if [ "$1" == "-d" ]
then
    shift
else
    nodebug=1
fi

showinfo()
{
    tput clear
    echo
    echo "-------------------------------------------------------------------"
    echo "----------- Regression tests for patterns in \`$1' ----------------"
    grep "^//" $1 | sed 's,^//[[:space:]]*,,'
    echo
    grep -v "^//" $1 > patterns
}

runflex()
{
    FLEX=`flex patterns 2>&1 | uniq`
    if [ "$FLEX" != "" ]
    then
        echo
        echo "flex reports:"
        echo "$FLEX"
        echo "(press Enter to continue)"
        read
    fi
}

runflexcpp()
{
    cat preamble patterns > lexer
    echo "Running ../tmp/bin/flexc++ -V lexer > out"
    ../tmp/bin/flexc++ -V lexer > out
}

makeprogram()
{
    [ "main.cc" -nt "main.o" ]  && g++ --std=c++0x -Wall -c main.cc

    g++ --std=c++0x -Wall main.o lex.cc 
}

runprogram()
{
    echo 
    echo "Running the regression tests using input file \`$1':"
    echo "(compiling)..."
    echo

    makeprogram

    echo "Press Enter to start the regression test"
    read
    ./a.out $1 $nodebug

    echo "Press Enter to continue"
    read
}

if [ $# == 0 ]
then
    list=`ls p[[:digit:]]*`
else
    list="$*"
fi

for file in $list
do
    showinfo $file
    echo "Run $file [Yn]? "
    read YES
    if [ "$YES" != n ]
    then
        data=`echo $file | sed 's/p/i/'`
        runflex 
        runflexcpp
        runprogram $data
    fi
done

rm -f a.out lex.cc lex.yy.c lexer main.o patterns scannerbase.h
