// Generated by Bisonc++ V4.01.00 on Fri, 11 May 2012 13:14:10 +0200

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them

// $insert debugincludes
#include <iostream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <iomanip>

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {306, 3}, // 1: input ->  opt_directives section_delimiter rules
     {308, 2}, // 2: section_delimiter (SECTION_DELIMITER) ->  SECTION_DELIMITER '\x0a'
     {310, 1}, // 3: identifier (IDENTIFIER) ->  IDENTIFIER
     {311, 0}, // 4: _sc_name ->  <empty>
     {312, 2}, // 5: _start_condition_type (INCL_START_CONDITION) ->  INCL_START_CONDITION _sc_name
     {312, 2}, // 6: _start_condition_type (EXCL_START_CONDITION) ->  EXCL_START_CONDITION _sc_name
     {313, 2}, // 7: _start_condition_names ->  _start_condition_names identifier
     {313, 1}, // 8: _start_condition_names ->  identifier
     {314, 2}, // 9: _start_condition_directive ->  _start_condition_type _start_condition_names
     {315, 1}, // 10: _name_def ->  identifier
     {316, 2}, // 11: _name_definition (STRING) ->  _name_def STRING
     {317, 1}, // 12: _directive ->  option
     {317, 1}, // 13: _directive ->  _start_condition_directive
     {317, 1}, // 14: _directive ->  _name_definition
     {317, 1}, // 15: _directive (_error_) ->  _error_
     {317, 0}, // 16: _directive ->  <empty>
     {319, 2}, // 17: _directive_line ('\x0a') ->  _directive '\x0a'
     {307, 2}, // 18: opt_directives ->  opt_directives _directive_line
     {307, 0}, // 19: opt_directives ->  <empty>
     {320, 1}, // 20: _baseclassheader (BASECLASSHEADER) ->  BASECLASSHEADER
     {321, 1}, // 21: _classheader (CLASSHEADER) ->  CLASSHEADER
     {322, 1}, // 22: _classname (CLASSNAME) ->  CLASSNAME
     {323, 1}, // 23: _filenames (FILENAMES) ->  FILENAMES
     {324, 1}, // 24: _implementationheader (IMPLEMENTATIONHEADER) ->  IMPLEMENTATIONHEADER
     {325, 1}, // 25: _inputinterface (INPUTINTERFACE) ->  INPUTINTERFACE
     {326, 1}, // 26: _inputimplementation (INPUTIMPLEMENTATION) ->  INPUTIMPLEMENTATION
     {327, 1}, // 27: _lexfunctionname (LEXFUNCTIONNAME) ->  LEXFUNCTIONNAME
     {328, 1}, // 28: _lexsource (LEXSOURCE) ->  LEXSOURCE
     {329, 1}, // 29: _namespace (NAMESPACE) ->  NAMESPACE
     {330, 1}, // 30: _skeleton_directory (SKELETON_DIRECTORY) ->  SKELETON_DIRECTORY
     {331, 1}, // 31: _target_directory (TARGET_DIRECTORY) ->  TARGET_DIRECTORY
     {332, 1}, // 32: _stringOrIdent (STRING) ->  STRING
     {332, 1}, // 33: _stringOrIdent (IDENTIFIER) ->  IDENTIFIER
     {333, 0}, // 34: _opt_is ->  <empty>
     {333, 1}, // 35: _opt_is ('=') ->  '='
     {318, 3}, // 36: option ->  _inputinterface _opt_is _stringOrIdent
     {318, 3}, // 37: option ->  _inputimplementation _opt_is _stringOrIdent
     {318, 3}, // 38: option ->  _classname _opt_is _stringOrIdent
     {318, 3}, // 39: option ->  _filenames _opt_is _stringOrIdent
     {318, 3}, // 40: option ->  _lexfunctionname _opt_is _stringOrIdent
     {318, 3}, // 41: option ->  _baseclassheader _opt_is _stringOrIdent
     {318, 3}, // 42: option ->  _classheader _opt_is _stringOrIdent
     {318, 3}, // 43: option ->  _implementationheader _opt_is _stringOrIdent
     {318, 3}, // 44: option ->  _lexsource _opt_is _stringOrIdent
     {318, 3}, // 45: option ->  _skeleton_directory _opt_is _stringOrIdent
     {318, 3}, // 46: option ->  _target_directory _opt_is _stringOrIdent
     {318, 3}, // 47: option ->  _namespace _opt_is _stringOrIdent
     {318, 1}, // 48: option (CASEINSENSITIVE) ->  CASEINSENSITIVE
     {318, 1}, // 49: option (INTERACTIVE) ->  INTERACTIVE
     {318, 1}, // 50: option (PRINT) ->  PRINT
     {318, 1}, // 51: option (NOLINES) ->  NOLINES
     {318, 1}, // 52: option (DEBUG) ->  DEBUG
     {334, 1}, // 53: combi_chars (',') ->  ','
     {334, 1}, // 54: combi_chars ('=') ->  '='
     {334, 1}, // 55: combi_chars ('-') ->  '-'
     {334, 1}, // 56: combi_chars (''') ->  '''
     {335, 1}, // 57: _ms_name ->  identifier
     {336, 3}, // 58: _ms_name_list (',') ->  _ms_name_list ',' _ms_name
     {336, 1}, // 59: _ms_name_list ->  _ms_name
     {337, 1}, // 60: _ms_specs ('*') ->  '*'
     {337, 1}, // 61: _ms_specs ->  _ms_name_list
     {338, 1}, // 62: _ms_angular ('<') ->  '<'
     {339, 4}, // 63: ms_spec ('>') ->  _ms_angular _ms_specs '>' reset
     {341, 0}, // 64: _m_contents ->  <empty>
     {342, 2}, // 65: _cc_start (CC_START) ->  CC_START _m_contents
     {343, 2}, // 66: _cc_negated (CC_NEGATED) ->  CC_NEGATED _m_contents
     {344, 1}, // 67: _cc_end (']') ->  ']'
     {345, 1}, // 68: _cc_literal ('/') ->  '/'
     {345, 1}, // 69: _cc_literal ('|') ->  '|'
     {345, 1}, // 70: _cc_literal ('(') ->  '('
     {345, 1}, // 71: _cc_literal (')') ->  ')'
     {345, 1}, // 72: _cc_literal ('*') ->  '*'
     {345, 1}, // 73: _cc_literal ('+') ->  '+'
     {345, 1}, // 74: _cc_literal ('?') ->  '?'
     {345, 1}, // 75: _cc_literal ('{') ->  '{'
     {345, 1}, // 76: _cc_literal ('}') ->  '}'
     {345, 1}, // 77: _cc_literal ('<') ->  '<'
     {345, 1}, // 78: _cc_literal ('>') ->  '>'
     {345, 1}, // 79: _cc_literal ('[') ->  '['
     {345, 1}, // 80: _cc_literal ('.') ->  '.'
     {345, 1}, // 81: _cc_literal ('^') ->  '^'
     {345, 1}, // 82: _cc_literal ('$') ->  '$'
     {345, 1}, // 83: _cc_literal (DOLLAR) ->  DOLLAR
     {345, 1}, // 84: _cc_literal (DECIMAL) ->  DECIMAL
     {345, 1}, // 85: _cc_literal (IDENTIFIER) ->  IDENTIFIER
     {345, 1}, // 86: _cc_literal (CHAR) ->  CHAR
     {345, 1}, // 87: _cc_literal (STRING) ->  STRING
     {345, 1}, // 88: _cc_literal ->  combi_chars
     {346, 1}, // 89: _cc_escape (ESCAPE_SEQUENCE) ->  ESCAPE_SEQUENCE
     {346, 1}, // 90: _cc_escape (QUOTES) ->  QUOTES
     {347, 1}, // 91: _cc_element ->  _cc_escape
     {347, 1}, // 92: _cc_element (PREDEFINED_CLASS) ->  PREDEFINED_CLASS
     {347, 1}, // 93: _cc_element ->  _cc_literal
     {348, 2}, // 94: _cc_contents ->  _cc_contents _cc_element
     {348, 1}, // 95: _cc_contents ->  _cc_element
     {349, 2}, // 96: _cc_set ->  _cc_start _cc_end
     {349, 2}, // 97: _cc_set ->  _cc_negated _cc_end
     {349, 3}, // 98: _cc_set ->  _cc_start _cc_contents _cc_end
     {349, 3}, // 99: _cc_set ->  _cc_negated _cc_contents _cc_end
     {350, 3}, // 100: characterclass (CC_PLUS) ->  characterclass CC_PLUS characterclass
     {350, 3}, // 101: characterclass (CC_MINUS) ->  characterclass CC_MINUS characterclass
     {350, 1}, // 102: characterclass ->  _cc_set
     {351, 1}, // 103: _decimal (DECIMAL) ->  DECIMAL
     {352, 1}, // 104: _interval ->  _decimal
     {352, 3}, // 105: _interval (',') ->  _decimal ',' _decimal
     {352, 2}, // 106: _interval (',') ->  _decimal ','
     {353, 1}, // 107: _single_char (CHAR) ->  CHAR
     {353, 1}, // 108: _single_char ->  combi_chars
     {354, 1}, // 109: _open_paren ('(') ->  '('
     {355, 1}, // 110: _close_paren (')') ->  ')'
     {356, 1}, // 111: _open_curly ('{') ->  '{'
     {357, 1}, // 112: _unit ('^') ->  '^'
     {357, 1}, // 113: _unit ('$') ->  '$'
     {357, 1}, // 114: _unit (DOLLAR) ->  DOLLAR
     {357, 1}, // 115: _unit (STRING) ->  STRING
     {357, 1}, // 116: _unit (QUOTES) ->  QUOTES
     {357, 1}, // 117: _unit (ESCAPE_SEQUENCE) ->  ESCAPE_SEQUENCE
     {357, 1}, // 118: _unit ('.') ->  '.'
     {357, 1}, // 119: _unit ->  _single_char
     {357, 1}, // 120: _unit ->  characterclass
     {358, 1}, // 121: _quantifier ('*') ->  '*'
     {358, 1}, // 122: _quantifier ('+') ->  '+'
     {358, 1}, // 123: _quantifier ('?') ->  '?'
     {359, 1}, // 124: _regex ->  _unit
     {359, 4}, // 125: _regex ('}') ->  _regex _open_curly _interval '}'
     {359, 2}, // 126: _regex ->  _regex _quantifier
     {359, 3}, // 127: _regex ->  _open_paren _regex _close_paren
     {359, 2}, // 128: _regex (CHAR) ->  _regex _regex
     {359, 3}, // 129: _regex ('|') ->  _regex '|' _regex
     {359, 3}, // 130: _regex ('/') ->  _regex '/' _regex
     {360, 1}, // 131: regexOrEOF ->  _regex
     {360, 1}, // 132: regexOrEOF (EOF_PATTERN) ->  EOF_PATTERN
     {361, 1}, // 133: action (BLOCK) ->  BLOCK
     {340, 0}, // 134: reset ->  <empty>
     {362, 5}, // 135: _msCompound_regex_list (ORNL) ->  _msCompound_regex_list ORNL '\x0a' reset _msCompound_regex_list
     {362, 1}, // 136: _msCompound_regex_list ->  regexOrEOF
     {363, 0}, // 137: _msCompound_rule ->  <empty>
     {363, 1}, // 138: _msCompound_rule ->  _msCompound_regex_list
     {363, 2}, // 139: _msCompound_rule ->  _msCompound_regex_list action
     {364, 3}, // 140: _msCompound_nl_rule ('\x0a') ->  _msCompound_rule '\x0a' reset
     {365, 0}, // 141: _opt_msCompound_nl_rules ->  <empty>
     {365, 2}, // 142: _opt_msCompound_nl_rules ->  _opt_msCompound_nl_rules _msCompound_nl_rule
     {366, 5}, // 143: msCompound ('{') ->  ms_spec '{' reset _opt_msCompound_nl_rules '}'
     {367, 2}, // 144: _optMs_regex ->  ms_spec regexOrEOF
     {367, 1}, // 145: _optMs_regex ->  regexOrEOF
     {368, 5}, // 146: _optMs_rule (ORNL) ->  _optMs_rule ORNL '\x0a' reset _optMs_rule
     {368, 1}, // 147: _optMs_rule ->  _optMs_regex
     {369, 1}, // 148: optMs_rule ->  _optMs_rule
     {369, 2}, // 149: optMs_rule ->  _optMs_rule action
     {370, 0}, // 150: _rule_def ->  <empty>
     {370, 1}, // 151: _rule_def (_error_) ->  _error_
     {370, 1}, // 152: _rule_def ->  optMs_rule
     {370, 1}, // 153: _rule_def ->  msCompound
     {371, 3}, // 154: _rule ('\x0a') ->  _rule_def '\x0a' reset
     {309, 2}, // 155: rules ->  rules _rule
     {309, 0}, // 156: rules ->  <empty>
     {372, 1}, // 157: input_$ ->  input
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { DEF_RED}, {   3} },                  
    { {     306}, {   1} }, // input         
    { {     307}, {   2} }, // opt_directives
    { {       0}, { -19} },                  
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { ERR_REQ_DEF}, {  44} },                              
    { {         308}, {   3} }, // section_delimiter         
    { {         319}, {   4} }, // _directive_line           
    { {         259}, {   5} }, // SECTION_DELIMITER         
    { {         317}, {   6} }, // _directive                
    { {         318}, {   7} }, // option                    
    { {         314}, {   8} }, // _start_condition_directive
    { {         316}, {   9} }, // _name_definition          
    { {     _error_}, {  10} }, // _error_                   
    { {         325}, {  11} }, // _inputinterface           
    { {         326}, {  12} }, // _inputimplementation      
    { {         322}, {  13} }, // _classname                
    { {         323}, {  14} }, // _filenames                
    { {         327}, {  15} }, // _lexfunctionname          
    { {         320}, {  16} }, // _baseclassheader          
    { {         321}, {  17} }, // _classheader              
    { {         324}, {  18} }, // _implementationheader     
    { {         328}, {  19} }, // _lexsource                
    { {         330}, {  20} }, // _skeleton_directory       
    { {         331}, {  21} }, // _target_directory         
    { {         329}, {  22} }, // _namespace                
    { {         261}, {  23} }, // CASEINSENSITIVE           
    { {         269}, {  24} }, // INTERACTIVE               
    { {         274}, {  25} }, // PRINT                     
    { {         273}, {  26} }, // NOLINES                   
    { {         264}, {  27} }, // DEBUG                     
    { {         312}, {  28} }, // _start_condition_type     
    { {         315}, {  29} }, // _name_def                 
    { {         268}, {  30} }, // INPUTINTERFACE            
    { {         267}, {  31} }, // INPUTIMPLEMENTATION       
    { {         263}, {  32} }, // CLASSNAME                 
    { {         265}, {  33} }, // FILENAMES                 
    { {         270}, {  34} }, // LEXFUNCTIONNAME           
    { {         260}, {  35} }, // BASECLASSHEADER           
    { {         262}, {  36} }, // CLASSHEADER               
    { {         266}, {  37} }, // IMPLEMENTATIONHEADER      
    { {         271}, {  38} }, // LEXSOURCE                 
    { {         275}, {  39} }, // SKELETON_DIRECTORY        
    { {         276}, {  40} }, // TARGET_DIRECTORY          
    { {         272}, {  41} }, // NAMESPACE                 
    { {         258}, {  42} }, // INCL_START_CONDITION      
    { {         257}, {  43} }, // EXCL_START_CONDITION      
    { {         310}, {  44} }, // identifier                
    { {         278}, {  45} }, // IDENTIFIER                
    { {           0}, { -16} },                              
};

SR__ s_3[] =
{
    { { DEF_RED}, {    2} },         
    { {     309}, {   46} }, // rules
    { {       0}, { -156} },         
};

SR__ s_4[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {        10}, { 47} }, // '\x0a'
    { {         0}, {  0} },          
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {        10}, { 48} }, // '\x0a'
    { {         0}, {  0} },          
};

SR__ s_7[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_11[] =
{
    { { REQ_DEF}, {   3} },           
    { {     333}, {  49} }, // _opt_is
    { {      61}, {  50} }, // '='    
    { {       0}, { -34} },           
};

SR__ s_12[] =
{
    { { REQ_DEF}, {   3} },           
    { {     333}, {  51} }, // _opt_is
    { {      61}, {  50} }, // '='    
    { {       0}, { -34} },           
};

SR__ s_13[] =
{
    { { REQ_DEF}, {   3} },           
    { {     333}, {  52} }, // _opt_is
    { {      61}, {  50} }, // '='    
    { {       0}, { -34} },           
};

SR__ s_14[] =
{
    { { REQ_DEF}, {   3} },           
    { {     333}, {  53} }, // _opt_is
    { {      61}, {  50} }, // '='    
    { {       0}, { -34} },           
};

SR__ s_15[] =
{
    { { REQ_DEF}, {   3} },           
    { {     333}, {  54} }, // _opt_is
    { {      61}, {  50} }, // '='    
    { {       0}, { -34} },           
};

SR__ s_16[] =
{
    { { REQ_DEF}, {   3} },           
    { {     333}, {  55} }, // _opt_is
    { {      61}, {  50} }, // '='    
    { {       0}, { -34} },           
};

SR__ s_17[] =
{
    { { REQ_DEF}, {   3} },           
    { {     333}, {  56} }, // _opt_is
    { {      61}, {  50} }, // '='    
    { {       0}, { -34} },           
};

SR__ s_18[] =
{
    { { REQ_DEF}, {   3} },           
    { {     333}, {  57} }, // _opt_is
    { {      61}, {  50} }, // '='    
    { {       0}, { -34} },           
};

SR__ s_19[] =
{
    { { REQ_DEF}, {   3} },           
    { {     333}, {  58} }, // _opt_is
    { {      61}, {  50} }, // '='    
    { {       0}, { -34} },           
};

SR__ s_20[] =
{
    { { REQ_DEF}, {   3} },           
    { {     333}, {  59} }, // _opt_is
    { {      61}, {  50} }, // '='    
    { {       0}, { -34} },           
};

SR__ s_21[] =
{
    { { REQ_DEF}, {   3} },           
    { {     333}, {  60} }, // _opt_is
    { {      61}, {  50} }, // '='    
    { {       0}, { -34} },           
};

SR__ s_22[] =
{
    { { REQ_DEF}, {   3} },           
    { {     333}, {  61} }, // _opt_is
    { {      61}, {  50} }, // '='    
    { {       0}, { -34} },           
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  4} },                          
    { {       313}, { 62} }, // _start_condition_names
    { {       310}, { 63} }, // identifier            
    { {       278}, { 45} }, // IDENTIFIER            
    { {         0}, {  0} },                          
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       280}, { 64} }, // STRING
    { {         0}, {  0} },          
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {  2} },            
    { {     311}, { 65} }, // _sc_name
    { {       0}, { -4} },            
};

SR__ s_43[] =
{
    { { DEF_RED}, {  2} },            
    { {     311}, { 66} }, // _sc_name
    { {       0}, { -4} },            
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_45[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_46[] =
{
    { { ERR_REQ_DEF}, {   38} },                   
    { {         371}, {   67} }, // _rule          
    { {         370}, {   68} }, // _rule_def      
    { {     _error_}, {   69} }, // _error_        
    { {         369}, {   70} }, // optMs_rule     
    { {         366}, {   71} }, // msCompound     
    { {         368}, {   72} }, // _optMs_rule    
    { {         339}, {   73} }, // ms_spec        
    { {         367}, {   74} }, // _optMs_regex   
    { {         338}, {   75} }, // _ms_angular    
    { {         360}, {   76} }, // regexOrEOF     
    { {          60}, {   77} }, // '<'            
    { {         359}, {   78} }, // _regex         
    { {         279}, {   79} }, // EOF_PATTERN    
    { {         357}, {   80} }, // _unit          
    { {         354}, {   81} }, // _open_paren    
    { {          94}, {   82} }, // '^'            
    { {          36}, {   83} }, // '$'            
    { {         283}, {   84} }, // DOLLAR         
    { {         280}, {   85} }, // STRING         
    { {         281}, {   86} }, // QUOTES         
    { {         284}, {   87} }, // ESCAPE_SEQUENCE
    { {          46}, {   88} }, // '.'            
    { {         353}, {   89} }, // _single_char   
    { {         350}, {   90} }, // characterclass 
    { {          40}, {   91} }, // '('            
    { {         289}, {   92} }, // CHAR           
    { {         334}, {   93} }, // combi_chars    
    { {         349}, {   94} }, // _cc_set        
    { {          44}, {   95} }, // ','            
    { {          61}, {   96} }, // '='            
    { {          45}, {   97} }, // '-'            
    { {          39}, {   98} }, // '''            
    { {         342}, {   99} }, // _cc_start      
    { {         343}, {  100} }, // _cc_negated    
    { {         285}, {  101} }, // CC_START       
    { {         286}, {  102} }, // CC_NEGATED     
    { {       _EOF_}, {   -1} }, // _EOF_          
    { {           0}, { -150} },                   
};

SR__ s_47[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {   4} },                  
    { {       332}, { 103} }, // _stringOrIdent
    { {       280}, { 104} }, // STRING        
    { {       278}, { 105} }, // IDENTIFIER    
    { {         0}, {   0} },                  
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {   4} },                  
    { {       332}, { 106} }, // _stringOrIdent
    { {       280}, { 104} }, // STRING        
    { {       278}, { 105} }, // IDENTIFIER    
    { {         0}, {   0} },                  
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {   4} },                  
    { {       332}, { 107} }, // _stringOrIdent
    { {       280}, { 104} }, // STRING        
    { {       278}, { 105} }, // IDENTIFIER    
    { {         0}, {   0} },                  
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {   4} },                  
    { {       332}, { 108} }, // _stringOrIdent
    { {       280}, { 104} }, // STRING        
    { {       278}, { 105} }, // IDENTIFIER    
    { {         0}, {   0} },                  
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {   4} },                  
    { {       332}, { 109} }, // _stringOrIdent
    { {       280}, { 104} }, // STRING        
    { {       278}, { 105} }, // IDENTIFIER    
    { {         0}, {   0} },                  
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {   4} },                  
    { {       332}, { 110} }, // _stringOrIdent
    { {       280}, { 104} }, // STRING        
    { {       278}, { 105} }, // IDENTIFIER    
    { {         0}, {   0} },                  
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {   4} },                  
    { {       332}, { 111} }, // _stringOrIdent
    { {       280}, { 104} }, // STRING        
    { {       278}, { 105} }, // IDENTIFIER    
    { {         0}, {   0} },                  
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {   4} },                  
    { {       332}, { 112} }, // _stringOrIdent
    { {       280}, { 104} }, // STRING        
    { {       278}, { 105} }, // IDENTIFIER    
    { {         0}, {   0} },                  
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {   4} },                  
    { {       332}, { 113} }, // _stringOrIdent
    { {       280}, { 104} }, // STRING        
    { {       278}, { 105} }, // IDENTIFIER    
    { {         0}, {   0} },                  
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {   4} },                  
    { {       332}, { 114} }, // _stringOrIdent
    { {       280}, { 104} }, // STRING        
    { {       278}, { 105} }, // IDENTIFIER    
    { {         0}, {   0} },                  
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {   4} },                  
    { {       332}, { 115} }, // _stringOrIdent
    { {       280}, { 104} }, // STRING        
    { {       278}, { 105} }, // IDENTIFIER    
    { {         0}, {   0} },                  
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {   4} },                  
    { {       332}, { 116} }, // _stringOrIdent
    { {       280}, { 104} }, // STRING        
    { {       278}, { 105} }, // IDENTIFIER    
    { {         0}, {   0} },                  
};

SR__ s_62[] =
{
    { { REQ_DEF}, {   3} },              
    { {     310}, { 117} }, // identifier
    { {     278}, {  45} }, // IDENTIFIER
    { {       0}, {  -9} },              
};

SR__ s_63[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_65[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_66[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_67[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -155} }, 
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 118} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_69[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -151} }, 
};

SR__ s_70[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -152} }, 
};

SR__ s_71[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -153} }, 
};

SR__ s_72[] =
{
    { { REQ_DEF}, {    4} },          
    { {     361}, {  119} }, // action
    { {     288}, {  120} }, // ORNL  
    { {     277}, {  121} }, // BLOCK 
    { {       0}, { -148} },          
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  28} },                   
    { {       123}, { 122} }, // '{'            
    { {       360}, { 123} }, // regexOrEOF     
    { {       359}, {  78} }, // _regex         
    { {       279}, {  79} }, // EOF_PATTERN    
    { {       357}, {  80} }, // _unit          
    { {       354}, {  81} }, // _open_paren    
    { {        94}, {  82} }, // '^'            
    { {        36}, {  83} }, // '$'            
    { {       283}, {  84} }, // DOLLAR         
    { {       280}, {  85} }, // STRING         
    { {       281}, {  86} }, // QUOTES         
    { {       284}, {  87} }, // ESCAPE_SEQUENCE
    { {        46}, {  88} }, // '.'            
    { {       353}, {  89} }, // _single_char   
    { {       350}, {  90} }, // characterclass 
    { {        40}, {  91} }, // '('            
    { {       289}, {  92} }, // CHAR           
    { {       334}, {  93} }, // combi_chars    
    { {       349}, {  94} }, // _cc_set        
    { {        44}, {  95} }, // ','            
    { {        61}, {  96} }, // '='            
    { {        45}, {  97} }, // '-'            
    { {        39}, {  98} }, // '''            
    { {       342}, {  99} }, // _cc_start      
    { {       343}, { 100} }, // _cc_negated    
    { {       285}, { 101} }, // CC_START       
    { {       286}, { 102} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_74[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -147} }, 
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {   7} },                 
    { {       337}, { 124} }, // _ms_specs    
    { {        42}, { 125} }, // '*'          
    { {       336}, { 126} }, // _ms_name_list
    { {       335}, { 127} }, // _ms_name     
    { {       310}, { 128} }, // identifier   
    { {       278}, {  45} }, // IDENTIFIER   
    { {         0}, {   0} },                 
};

SR__ s_76[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -145} }, 
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -62} }, 
};

SR__ s_78[] =
{
    { { REQ_DEF}, {   33} },                   
    { {     356}, {  129} }, // _open_curly    
    { {     358}, {  130} }, // _quantifier    
    { {     359}, {  131} }, // _regex         
    { {     124}, {  132} }, // '|'            
    { {      47}, {  133} }, // '/'            
    { {     123}, {  134} }, // '{'            
    { {      42}, {  135} }, // '*'            
    { {      43}, {  136} }, // '+'            
    { {      63}, {  137} }, // '?'            
    { {     357}, {   80} }, // _unit          
    { {     354}, {   81} }, // _open_paren    
    { {      94}, {   82} }, // '^'            
    { {      36}, {   83} }, // '$'            
    { {     283}, {   84} }, // DOLLAR         
    { {     280}, {   85} }, // STRING         
    { {     281}, {   86} }, // QUOTES         
    { {     284}, {   87} }, // ESCAPE_SEQUENCE
    { {      46}, {   88} }, // '.'            
    { {     353}, {   89} }, // _single_char   
    { {     350}, {   90} }, // characterclass 
    { {      40}, {   91} }, // '('            
    { {     289}, {   92} }, // CHAR           
    { {     334}, {   93} }, // combi_chars    
    { {     349}, {   94} }, // _cc_set        
    { {      44}, {   95} }, // ','            
    { {      61}, {   96} }, // '='            
    { {      45}, {   97} }, // '-'            
    { {      39}, {   98} }, // '''            
    { {     342}, {   99} }, // _cc_start      
    { {     343}, {  100} }, // _cc_negated    
    { {     285}, {  101} }, // CC_START       
    { {     286}, {  102} }, // CC_NEGATED     
    { {       0}, { -131} },                   
};

SR__ s_79[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -132} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -124} }, 
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  25} },                   
    { {       359}, { 138} }, // _regex         
    { {       357}, {  80} }, // _unit          
    { {       354}, {  81} }, // _open_paren    
    { {        94}, {  82} }, // '^'            
    { {        36}, {  83} }, // '$'            
    { {       283}, {  84} }, // DOLLAR         
    { {       280}, {  85} }, // STRING         
    { {       281}, {  86} }, // QUOTES         
    { {       284}, {  87} }, // ESCAPE_SEQUENCE
    { {        46}, {  88} }, // '.'            
    { {       353}, {  89} }, // _single_char   
    { {       350}, {  90} }, // characterclass 
    { {        40}, {  91} }, // '('            
    { {       289}, {  92} }, // CHAR           
    { {       334}, {  93} }, // combi_chars    
    { {       349}, {  94} }, // _cc_set        
    { {        44}, {  95} }, // ','            
    { {        61}, {  96} }, // '='            
    { {        45}, {  97} }, // '-'            
    { {        39}, {  98} }, // '''            
    { {       342}, {  99} }, // _cc_start      
    { {       343}, { 100} }, // _cc_negated    
    { {       285}, { 101} }, // CC_START       
    { {       286}, { 102} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_82[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -112} }, 
};

SR__ s_83[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -113} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -114} }, 
};

SR__ s_85[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -115} }, 
};

SR__ s_86[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -116} }, 
};

SR__ s_87[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -117} }, 
};

SR__ s_88[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -118} }, 
};

SR__ s_89[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -119} }, 
};

SR__ s_90[] =
{
    { { REQ_DEF}, {    3} },            
    { {     290}, {  139} }, // CC_PLUS 
    { {     291}, {  140} }, // CC_MINUS
    { {       0}, { -120} },            
};

SR__ s_91[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -109} }, 
};

SR__ s_92[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -107} }, 
};

SR__ s_93[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -108} }, 
};

SR__ s_94[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -102} }, 
};

SR__ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_99[] =
{
    { { REQ_TOKEN}, {  35} },                    
    { {       344}, { 141} }, // _cc_end         
    { {       348}, { 142} }, // _cc_contents    
    { {        93}, { 143} }, // ']'             
    { {       347}, { 144} }, // _cc_element     
    { {       346}, { 145} }, // _cc_escape      
    { {       287}, { 146} }, // PREDEFINED_CLASS
    { {       345}, { 147} }, // _cc_literal     
    { {       284}, { 148} }, // ESCAPE_SEQUENCE 
    { {       281}, { 149} }, // QUOTES          
    { {        47}, { 150} }, // '/'             
    { {       124}, { 151} }, // '|'             
    { {        40}, { 152} }, // '('             
    { {        41}, { 153} }, // ')'             
    { {        42}, { 154} }, // '*'             
    { {        43}, { 155} }, // '+'             
    { {        63}, { 156} }, // '?'             
    { {       123}, { 157} }, // '{'             
    { {       125}, { 158} }, // '}'             
    { {        60}, { 159} }, // '<'             
    { {        62}, { 160} }, // '>'             
    { {        91}, { 161} }, // '['             
    { {        46}, { 162} }, // '.'             
    { {        94}, { 163} }, // '^'             
    { {        36}, { 164} }, // '$'             
    { {       283}, { 165} }, // DOLLAR          
    { {       282}, { 166} }, // DECIMAL         
    { {       278}, { 167} }, // IDENTIFIER      
    { {       289}, { 168} }, // CHAR            
    { {       280}, { 169} }, // STRING          
    { {       334}, { 170} }, // combi_chars     
    { {        44}, {  95} }, // ','             
    { {        61}, {  96} }, // '='             
    { {        45}, {  97} }, // '-'             
    { {        39}, {  98} }, // '''             
    { {         0}, {   0} },                    
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {  35} },                    
    { {       344}, { 171} }, // _cc_end         
    { {       348}, { 172} }, // _cc_contents    
    { {        93}, { 143} }, // ']'             
    { {       347}, { 144} }, // _cc_element     
    { {       346}, { 145} }, // _cc_escape      
    { {       287}, { 146} }, // PREDEFINED_CLASS
    { {       345}, { 147} }, // _cc_literal     
    { {       284}, { 148} }, // ESCAPE_SEQUENCE 
    { {       281}, { 149} }, // QUOTES          
    { {        47}, { 150} }, // '/'             
    { {       124}, { 151} }, // '|'             
    { {        40}, { 152} }, // '('             
    { {        41}, { 153} }, // ')'             
    { {        42}, { 154} }, // '*'             
    { {        43}, { 155} }, // '+'             
    { {        63}, { 156} }, // '?'             
    { {       123}, { 157} }, // '{'             
    { {       125}, { 158} }, // '}'             
    { {        60}, { 159} }, // '<'             
    { {        62}, { 160} }, // '>'             
    { {        91}, { 161} }, // '['             
    { {        46}, { 162} }, // '.'             
    { {        94}, { 163} }, // '^'             
    { {        36}, { 164} }, // '$'             
    { {       283}, { 165} }, // DOLLAR          
    { {       282}, { 166} }, // DECIMAL         
    { {       278}, { 167} }, // IDENTIFIER      
    { {       289}, { 168} }, // CHAR            
    { {       280}, { 169} }, // STRING          
    { {       334}, { 170} }, // combi_chars     
    { {        44}, {  95} }, // ','             
    { {        61}, {  96} }, // '='             
    { {        45}, {  97} }, // '-'             
    { {        39}, {  98} }, // '''             
    { {         0}, {   0} },                    
};

SR__ s_101[] =
{
    { { DEF_RED}, {   2} },               
    { {     341}, { 173} }, // _m_contents
    { {       0}, { -64} },               
};

SR__ s_102[] =
{
    { { DEF_RED}, {   2} },               
    { {     341}, { 174} }, // _m_contents
    { {       0}, { -64} },               
};

SR__ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_104[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_107[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_108[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_109[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_110[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_111[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_112[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_113[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_114[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_115[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_116[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_117[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_118[] =
{
    { { DEF_RED}, {    2} },         
    { {     340}, {  175} }, // reset
    { {       0}, { -134} },         
};

SR__ s_119[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -149} }, 
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 176} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_121[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -133} }, 
};

SR__ s_122[] =
{
    { { DEF_RED}, {    2} },         
    { {     340}, {  177} }, // reset
    { {       0}, { -134} },         
};

SR__ s_123[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -144} }, 
};

SR__ s_124[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        62}, { 178} }, // '>'
    { {         0}, {   0} },       
};

SR__ s_125[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_126[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, { 179} }, // ','
    { {       0}, { -61} },       
};

SR__ s_127[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_128[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_129[] =
{
    { { REQ_TOKEN}, {   4} },             
    { {       352}, { 180} }, // _interval
    { {       351}, { 181} }, // _decimal 
    { {       282}, { 182} }, // DECIMAL  
    { {         0}, {   0} },             
};

SR__ s_130[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -126} }, 
};

SR__ s_131[] =
{
    { { REQ_DEF}, {   16} },                  
    { {     356}, {  129} }, // _open_curly   
    { {     358}, {  130} }, // _quantifier   
    { {     359}, {  131} }, // _regex        
    { {     123}, {  134} }, // '{'           
    { {      42}, {  135} }, // '*'           
    { {      43}, {  136} }, // '+'           
    { {      63}, {  137} }, // '?'           
    { {     357}, {   80} }, // _unit         
    { {     354}, {   81} }, // _open_paren   
    { {     353}, {   89} }, // _single_char  
    { {     350}, {   90} }, // characterclass
    { {     334}, {   93} }, // combi_chars   
    { {     349}, {   94} }, // _cc_set       
    { {     342}, {   99} }, // _cc_start     
    { {     343}, {  100} }, // _cc_negated   
    { {       0}, { -128} },                  
};

SR__ s_132[] =
{
    { { REQ_TOKEN}, {  25} },                   
    { {       359}, { 183} }, // _regex         
    { {       357}, {  80} }, // _unit          
    { {       354}, {  81} }, // _open_paren    
    { {        94}, {  82} }, // '^'            
    { {        36}, {  83} }, // '$'            
    { {       283}, {  84} }, // DOLLAR         
    { {       280}, {  85} }, // STRING         
    { {       281}, {  86} }, // QUOTES         
    { {       284}, {  87} }, // ESCAPE_SEQUENCE
    { {        46}, {  88} }, // '.'            
    { {       353}, {  89} }, // _single_char   
    { {       350}, {  90} }, // characterclass 
    { {        40}, {  91} }, // '('            
    { {       289}, {  92} }, // CHAR           
    { {       334}, {  93} }, // combi_chars    
    { {       349}, {  94} }, // _cc_set        
    { {        44}, {  95} }, // ','            
    { {        61}, {  96} }, // '='            
    { {        45}, {  97} }, // '-'            
    { {        39}, {  98} }, // '''            
    { {       342}, {  99} }, // _cc_start      
    { {       343}, { 100} }, // _cc_negated    
    { {       285}, { 101} }, // CC_START       
    { {       286}, { 102} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_133[] =
{
    { { REQ_TOKEN}, {  25} },                   
    { {       359}, { 184} }, // _regex         
    { {       357}, {  80} }, // _unit          
    { {       354}, {  81} }, // _open_paren    
    { {        94}, {  82} }, // '^'            
    { {        36}, {  83} }, // '$'            
    { {       283}, {  84} }, // DOLLAR         
    { {       280}, {  85} }, // STRING         
    { {       281}, {  86} }, // QUOTES         
    { {       284}, {  87} }, // ESCAPE_SEQUENCE
    { {        46}, {  88} }, // '.'            
    { {       353}, {  89} }, // _single_char   
    { {       350}, {  90} }, // characterclass 
    { {        40}, {  91} }, // '('            
    { {       289}, {  92} }, // CHAR           
    { {       334}, {  93} }, // combi_chars    
    { {       349}, {  94} }, // _cc_set        
    { {        44}, {  95} }, // ','            
    { {        61}, {  96} }, // '='            
    { {        45}, {  97} }, // '-'            
    { {        39}, {  98} }, // '''            
    { {       342}, {  99} }, // _cc_start      
    { {       343}, { 100} }, // _cc_negated    
    { {       285}, { 101} }, // CC_START       
    { {       286}, { 102} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_134[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -111} }, 
};

SR__ s_135[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -121} }, 
};

SR__ s_136[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -122} }, 
};

SR__ s_137[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -123} }, 
};

SR__ s_138[] =
{
    { { REQ_TOKEN}, {  35} },                   
    { {       355}, { 185} }, // _close_paren   
    { {       356}, { 129} }, // _open_curly    
    { {       358}, { 130} }, // _quantifier    
    { {       359}, { 131} }, // _regex         
    { {       124}, { 132} }, // '|'            
    { {        47}, { 133} }, // '/'            
    { {        41}, { 186} }, // ')'            
    { {       123}, { 134} }, // '{'            
    { {        42}, { 135} }, // '*'            
    { {        43}, { 136} }, // '+'            
    { {        63}, { 137} }, // '?'            
    { {       357}, {  80} }, // _unit          
    { {       354}, {  81} }, // _open_paren    
    { {        94}, {  82} }, // '^'            
    { {        36}, {  83} }, // '$'            
    { {       283}, {  84} }, // DOLLAR         
    { {       280}, {  85} }, // STRING         
    { {       281}, {  86} }, // QUOTES         
    { {       284}, {  87} }, // ESCAPE_SEQUENCE
    { {        46}, {  88} }, // '.'            
    { {       353}, {  89} }, // _single_char   
    { {       350}, {  90} }, // characterclass 
    { {        40}, {  91} }, // '('            
    { {       289}, {  92} }, // CHAR           
    { {       334}, {  93} }, // combi_chars    
    { {       349}, {  94} }, // _cc_set        
    { {        44}, {  95} }, // ','            
    { {        61}, {  96} }, // '='            
    { {        45}, {  97} }, // '-'            
    { {        39}, {  98} }, // '''            
    { {       342}, {  99} }, // _cc_start      
    { {       343}, { 100} }, // _cc_negated    
    { {       285}, { 101} }, // CC_START       
    { {       286}, { 102} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_139[] =
{
    { { REQ_TOKEN}, {   7} },                  
    { {       350}, { 187} }, // characterclass
    { {       349}, {  94} }, // _cc_set       
    { {       342}, {  99} }, // _cc_start     
    { {       343}, { 100} }, // _cc_negated   
    { {       285}, { 101} }, // CC_START      
    { {       286}, { 102} }, // CC_NEGATED    
    { {         0}, {   0} },                  
};

SR__ s_140[] =
{
    { { REQ_TOKEN}, {   7} },                  
    { {       350}, { 188} }, // characterclass
    { {       349}, {  94} }, // _cc_set       
    { {       342}, {  99} }, // _cc_start     
    { {       343}, { 100} }, // _cc_negated   
    { {       285}, { 101} }, // CC_START      
    { {       286}, { 102} }, // CC_NEGATED    
    { {         0}, {   0} },                  
};

SR__ s_141[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -96} }, 
};

SR__ s_142[] =
{
    { { REQ_TOKEN}, {  34} },                    
    { {       344}, { 189} }, // _cc_end         
    { {       347}, { 190} }, // _cc_element     
    { {        93}, { 143} }, // ']'             
    { {       346}, { 145} }, // _cc_escape      
    { {       287}, { 146} }, // PREDEFINED_CLASS
    { {       345}, { 147} }, // _cc_literal     
    { {       284}, { 148} }, // ESCAPE_SEQUENCE 
    { {       281}, { 149} }, // QUOTES          
    { {        47}, { 150} }, // '/'             
    { {       124}, { 151} }, // '|'             
    { {        40}, { 152} }, // '('             
    { {        41}, { 153} }, // ')'             
    { {        42}, { 154} }, // '*'             
    { {        43}, { 155} }, // '+'             
    { {        63}, { 156} }, // '?'             
    { {       123}, { 157} }, // '{'             
    { {       125}, { 158} }, // '}'             
    { {        60}, { 159} }, // '<'             
    { {        62}, { 160} }, // '>'             
    { {        91}, { 161} }, // '['             
    { {        46}, { 162} }, // '.'             
    { {        94}, { 163} }, // '^'             
    { {        36}, { 164} }, // '$'             
    { {       283}, { 165} }, // DOLLAR          
    { {       282}, { 166} }, // DECIMAL         
    { {       278}, { 167} }, // IDENTIFIER      
    { {       289}, { 168} }, // CHAR            
    { {       280}, { 169} }, // STRING          
    { {       334}, { 170} }, // combi_chars     
    { {        44}, {  95} }, // ','             
    { {        61}, {  96} }, // '='             
    { {        45}, {  97} }, // '-'             
    { {        39}, {  98} }, // '''             
    { {         0}, {   0} },                    
};

SR__ s_143[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_144[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -95} }, 
};

SR__ s_145[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -91} }, 
};

SR__ s_146[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -92} }, 
};

SR__ s_147[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -93} }, 
};

SR__ s_148[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -89} }, 
};

SR__ s_149[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -90} }, 
};

SR__ s_150[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_151[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_152[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR__ s_153[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_154[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR__ s_155[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -73} }, 
};

SR__ s_156[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -74} }, 
};

SR__ s_157[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -75} }, 
};

SR__ s_158[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -76} }, 
};

SR__ s_159[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -77} }, 
};

SR__ s_160[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -78} }, 
};

SR__ s_161[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -79} }, 
};

SR__ s_162[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -80} }, 
};

SR__ s_163[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -81} }, 
};

SR__ s_164[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -82} }, 
};

SR__ s_165[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -83} }, 
};

SR__ s_166[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -84} }, 
};

SR__ s_167[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -85} }, 
};

SR__ s_168[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -86} }, 
};

SR__ s_169[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -87} }, 
};

SR__ s_170[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -88} }, 
};

SR__ s_171[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -97} }, 
};

SR__ s_172[] =
{
    { { REQ_TOKEN}, {  34} },                    
    { {       344}, { 191} }, // _cc_end         
    { {       347}, { 190} }, // _cc_element     
    { {        93}, { 143} }, // ']'             
    { {       346}, { 145} }, // _cc_escape      
    { {       287}, { 146} }, // PREDEFINED_CLASS
    { {       345}, { 147} }, // _cc_literal     
    { {       284}, { 148} }, // ESCAPE_SEQUENCE 
    { {       281}, { 149} }, // QUOTES          
    { {        47}, { 150} }, // '/'             
    { {       124}, { 151} }, // '|'             
    { {        40}, { 152} }, // '('             
    { {        41}, { 153} }, // ')'             
    { {        42}, { 154} }, // '*'             
    { {        43}, { 155} }, // '+'             
    { {        63}, { 156} }, // '?'             
    { {       123}, { 157} }, // '{'             
    { {       125}, { 158} }, // '}'             
    { {        60}, { 159} }, // '<'             
    { {        62}, { 160} }, // '>'             
    { {        91}, { 161} }, // '['             
    { {        46}, { 162} }, // '.'             
    { {        94}, { 163} }, // '^'             
    { {        36}, { 164} }, // '$'             
    { {       283}, { 165} }, // DOLLAR          
    { {       282}, { 166} }, // DECIMAL         
    { {       278}, { 167} }, // IDENTIFIER      
    { {       289}, { 168} }, // CHAR            
    { {       280}, { 169} }, // STRING          
    { {       334}, { 170} }, // combi_chars     
    { {        44}, {  95} }, // ','             
    { {        61}, {  96} }, // '='             
    { {        45}, {  97} }, // '-'             
    { {        39}, {  98} }, // '''             
    { {         0}, {   0} },                    
};

SR__ s_173[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_174[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_175[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -154} }, 
};

SR__ s_176[] =
{
    { { DEF_RED}, {    2} },         
    { {     340}, {  192} }, // reset
    { {       0}, { -134} },         
};

SR__ s_177[] =
{
    { { DEF_RED}, {    2} },                            
    { {     365}, {  193} }, // _opt_msCompound_nl_rules
    { {       0}, { -141} },                            
};

SR__ s_178[] =
{
    { { DEF_RED}, {    2} },         
    { {     340}, {  194} }, // reset
    { {       0}, { -134} },         
};

SR__ s_179[] =
{
    { { REQ_TOKEN}, {   4} },              
    { {       335}, { 195} }, // _ms_name  
    { {       310}, { 128} }, // identifier
    { {       278}, {  45} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR__ s_180[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       125}, { 196} }, // '}'
    { {         0}, {   0} },       
};

SR__ s_181[] =
{
    { { REQ_DEF}, {    2} },       
    { {      44}, {  197} }, // ','
    { {       0}, { -104} },       
};

SR__ s_182[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -103} }, 
};

SR__ s_183[] =
{
    { { REQ_DEF}, {   17} },                  
    { {     356}, {  129} }, // _open_curly   
    { {     358}, {  130} }, // _quantifier   
    { {     359}, {  131} }, // _regex        
    { {     123}, {  134} }, // '{'           
    { {      42}, {  135} }, // '*'           
    { {      43}, {  136} }, // '+'           
    { {      63}, {  137} }, // '?'           
    { {     357}, {   80} }, // _unit         
    { {     354}, {   81} }, // _open_paren   
    { {     353}, {   89} }, // _single_char  
    { {     350}, {   90} }, // characterclass
    { {     289}, {   92} }, // CHAR          
    { {     334}, {   93} }, // combi_chars   
    { {     349}, {   94} }, // _cc_set       
    { {     342}, {   99} }, // _cc_start     
    { {     343}, {  100} }, // _cc_negated   
    { {       0}, { -129} },                  
};

SR__ s_184[] =
{
    { { REQ_DEF}, {   18} },                  
    { {     356}, {  129} }, // _open_curly   
    { {     358}, {  130} }, // _quantifier   
    { {     359}, {  131} }, // _regex        
    { {     124}, {  132} }, // '|'           
    { {     123}, {  134} }, // '{'           
    { {      42}, {  135} }, // '*'           
    { {      43}, {  136} }, // '+'           
    { {      63}, {  137} }, // '?'           
    { {     357}, {   80} }, // _unit         
    { {     354}, {   81} }, // _open_paren   
    { {     353}, {   89} }, // _single_char  
    { {     350}, {   90} }, // characterclass
    { {     289}, {   92} }, // CHAR          
    { {     334}, {   93} }, // combi_chars   
    { {     349}, {   94} }, // _cc_set       
    { {     342}, {   99} }, // _cc_start     
    { {     343}, {  100} }, // _cc_negated   
    { {       0}, { -130} },                  
};

SR__ s_185[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -127} }, 
};

SR__ s_186[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -110} }, 
};

SR__ s_187[] =
{
    { { REQ_DEF}, {    1} }, 
    { {       0}, { -100} }, 
};

SR__ s_188[] =
{
    { { REQ_DEF}, {    1} }, 
    { {       0}, { -101} }, 
};

SR__ s_189[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -98} }, 
};

SR__ s_190[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -94} }, 
};

SR__ s_191[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -99} }, 
};

SR__ s_192[] =
{
    { { REQ_TOKEN}, {  32} },                   
    { {       368}, { 198} }, // _optMs_rule    
    { {       367}, {  74} }, // _optMs_regex   
    { {       339}, { 199} }, // ms_spec        
    { {       360}, {  76} }, // regexOrEOF     
    { {       338}, {  75} }, // _ms_angular    
    { {       359}, {  78} }, // _regex         
    { {       279}, {  79} }, // EOF_PATTERN    
    { {        60}, {  77} }, // '<'            
    { {       357}, {  80} }, // _unit          
    { {       354}, {  81} }, // _open_paren    
    { {        94}, {  82} }, // '^'            
    { {        36}, {  83} }, // '$'            
    { {       283}, {  84} }, // DOLLAR         
    { {       280}, {  85} }, // STRING         
    { {       281}, {  86} }, // QUOTES         
    { {       284}, {  87} }, // ESCAPE_SEQUENCE
    { {        46}, {  88} }, // '.'            
    { {       353}, {  89} }, // _single_char   
    { {       350}, {  90} }, // characterclass 
    { {        40}, {  91} }, // '('            
    { {       289}, {  92} }, // CHAR           
    { {       334}, {  93} }, // combi_chars    
    { {       349}, {  94} }, // _cc_set        
    { {        44}, {  95} }, // ','            
    { {        61}, {  96} }, // '='            
    { {        45}, {  97} }, // '-'            
    { {        39}, {  98} }, // '''            
    { {       342}, {  99} }, // _cc_start      
    { {       343}, { 100} }, // _cc_negated    
    { {       285}, { 101} }, // CC_START       
    { {       286}, { 102} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_193[] =
{
    { { REQ_DEF}, {   31} },                          
    { {     125}, {  200} }, // '}'                   
    { {     364}, {  201} }, // _msCompound_nl_rule   
    { {     363}, {  202} }, // _msCompound_rule      
    { {     362}, {  203} }, // _msCompound_regex_list
    { {     360}, {  204} }, // regexOrEOF            
    { {     359}, {   78} }, // _regex                
    { {     279}, {   79} }, // EOF_PATTERN           
    { {     357}, {   80} }, // _unit                 
    { {     354}, {   81} }, // _open_paren           
    { {      94}, {   82} }, // '^'                   
    { {      36}, {   83} }, // '$'                   
    { {     283}, {   84} }, // DOLLAR                
    { {     280}, {   85} }, // STRING                
    { {     281}, {   86} }, // QUOTES                
    { {     284}, {   87} }, // ESCAPE_SEQUENCE       
    { {      46}, {   88} }, // '.'                   
    { {     353}, {   89} }, // _single_char          
    { {     350}, {   90} }, // characterclass        
    { {      40}, {   91} }, // '('                   
    { {     289}, {   92} }, // CHAR                  
    { {     334}, {   93} }, // combi_chars           
    { {     349}, {   94} }, // _cc_set               
    { {      44}, {   95} }, // ','                   
    { {      61}, {   96} }, // '='                   
    { {      45}, {   97} }, // '-'                   
    { {      39}, {   98} }, // '''                   
    { {     342}, {   99} }, // _cc_start             
    { {     343}, {  100} }, // _cc_negated           
    { {     285}, {  101} }, // CC_START              
    { {     286}, {  102} }, // CC_NEGATED            
    { {       0}, { -137} },                          
};

SR__ s_194[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_195[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_196[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -125} }, 
};

SR__ s_197[] =
{
    { { REQ_DEF}, {    3} },            
    { {     351}, {  205} }, // _decimal
    { {     282}, {  182} }, // DECIMAL 
    { {       0}, { -106} },            
};

SR__ s_198[] =
{
    { { REQ_DEF}, {    1} }, 
    { {       0}, { -146} }, 
};

SR__ s_199[] =
{
    { { REQ_TOKEN}, {  27} },                   
    { {       360}, { 123} }, // regexOrEOF     
    { {       359}, {  78} }, // _regex         
    { {       279}, {  79} }, // EOF_PATTERN    
    { {       357}, {  80} }, // _unit          
    { {       354}, {  81} }, // _open_paren    
    { {        94}, {  82} }, // '^'            
    { {        36}, {  83} }, // '$'            
    { {       283}, {  84} }, // DOLLAR         
    { {       280}, {  85} }, // STRING         
    { {       281}, {  86} }, // QUOTES         
    { {       284}, {  87} }, // ESCAPE_SEQUENCE
    { {        46}, {  88} }, // '.'            
    { {       353}, {  89} }, // _single_char   
    { {       350}, {  90} }, // characterclass 
    { {        40}, {  91} }, // '('            
    { {       289}, {  92} }, // CHAR           
    { {       334}, {  93} }, // combi_chars    
    { {       349}, {  94} }, // _cc_set        
    { {        44}, {  95} }, // ','            
    { {        61}, {  96} }, // '='            
    { {        45}, {  97} }, // '-'            
    { {        39}, {  98} }, // '''            
    { {       342}, {  99} }, // _cc_start      
    { {       343}, { 100} }, // _cc_negated    
    { {       285}, { 101} }, // CC_START       
    { {       286}, { 102} }, // CC_NEGATED     
    { {         0}, {   0} },                   
};

SR__ s_200[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -143} }, 
};

SR__ s_201[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -142} }, 
};

SR__ s_202[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 206} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_203[] =
{
    { { REQ_DEF}, {    4} },          
    { {     361}, {  207} }, // action
    { {     288}, {  208} }, // ORNL  
    { {     277}, {  121} }, // BLOCK 
    { {       0}, { -138} },          
};

SR__ s_204[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -136} }, 
};

SR__ s_205[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -105} }, 
};

SR__ s_206[] =
{
    { { DEF_RED}, {    2} },         
    { {     340}, {  209} }, // reset
    { {       0}, { -134} },         
};

SR__ s_207[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -139} }, 
};

SR__ s_208[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {        10}, { 210} }, // '\x0a'
    { {         0}, {   0} },          
};

SR__ s_209[] =
{
    { { DEF_RED}, {    1} }, 
    { {       0}, { -140} }, 
};

SR__ s_210[] =
{
    { { DEF_RED}, {    2} },         
    { {     340}, {  211} }, // reset
    { {       0}, { -134} },         
};

SR__ s_211[] =
{
    { { REQ_TOKEN}, {  28} },                          
    { {       362}, { 212} }, // _msCompound_regex_list
    { {       360}, { 204} }, // regexOrEOF            
    { {       359}, {  78} }, // _regex                
    { {       279}, {  79} }, // EOF_PATTERN           
    { {       357}, {  80} }, // _unit                 
    { {       354}, {  81} }, // _open_paren           
    { {        94}, {  82} }, // '^'                   
    { {        36}, {  83} }, // '$'                   
    { {       283}, {  84} }, // DOLLAR                
    { {       280}, {  85} }, // STRING                
    { {       281}, {  86} }, // QUOTES                
    { {       284}, {  87} }, // ESCAPE_SEQUENCE       
    { {        46}, {  88} }, // '.'                   
    { {       353}, {  89} }, // _single_char          
    { {       350}, {  90} }, // characterclass        
    { {        40}, {  91} }, // '('                   
    { {       289}, {  92} }, // CHAR                  
    { {       334}, {  93} }, // combi_chars           
    { {       349}, {  94} }, // _cc_set               
    { {        44}, {  95} }, // ','                   
    { {        61}, {  96} }, // '='                   
    { {        45}, {  97} }, // '-'                   
    { {        39}, {  98} }, // '''                   
    { {       342}, {  99} }, // _cc_start             
    { {       343}, { 100} }, // _cc_negated           
    { {       285}, { 101} }, // CC_START              
    { {       286}, { 102} }, // CC_NEGATED            
    { {         0}, {   0} },                          
};

SR__ s_212[] =
{
    { { REQ_DEF}, {    1} }, 
    { {       0}, { -135} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,  s_153,  s_154,  s_155,  s_156,  s_157,  s_158,  s_159,
  s_160,  s_161,  s_162,  s_163,  s_164,  s_165,  s_166,  s_167,  s_168,  s_169,
  s_170,  s_171,  s_172,  s_173,  s_174,  s_175,  s_176,  s_177,  s_178,  s_179,
  s_180,  s_181,  s_182,  s_183,  s_184,  s_185,  s_186,  s_187,  s_188,  s_189,
  s_190,  s_191,  s_192,  s_193,  s_194,  s_195,  s_196,  s_197,  s_198,  s_199,
  s_200,  s_201,  s_202,  s_203,  s_204,  s_205,  s_206,  s_207,  s_208,  s_209,
  s_210,  s_211,  s_212,
};

typedef std::unordered_map<int, char const *> SMap;
typedef SMap::value_type SMapVal;

SMapVal s_symArr[] =
{
    SMapVal(-2, "_UNDETERMINED_"),  // predefined symbols
    SMapVal(-1, "_EOF_"),
    SMapVal(256, "_error_"),

    SMapVal(257, "EXCL_START_CONDITION"),
    SMapVal(258, "INCL_START_CONDITION"),
    SMapVal(259, "SECTION_DELIMITER"),
    SMapVal(260, "BASECLASSHEADER"),
    SMapVal(261, "CASEINSENSITIVE"),
    SMapVal(262, "CLASSHEADER"),
    SMapVal(263, "CLASSNAME"),
    SMapVal(264, "DEBUG"),
    SMapVal(265, "FILENAMES"),
    SMapVal(266, "IMPLEMENTATIONHEADER"),
    SMapVal(267, "INPUTIMPLEMENTATION"),
    SMapVal(268, "INPUTINTERFACE"),
    SMapVal(269, "INTERACTIVE"),
    SMapVal(270, "LEXFUNCTIONNAME"),
    SMapVal(271, "LEXSOURCE"),
    SMapVal(272, "NAMESPACE"),
    SMapVal(273, "NOLINES"),
    SMapVal(274, "PRINT"),
    SMapVal(275, "SKELETON_DIRECTORY"),
    SMapVal(276, "TARGET_DIRECTORY"),
    SMapVal(277, "BLOCK"),
    SMapVal(278, "IDENTIFIER"),
    SMapVal(279, "EOF_PATTERN"),
    SMapVal(280, "STRING"),
    SMapVal(281, "QUOTES"),
    SMapVal(282, "DECIMAL"),
    SMapVal(283, "DOLLAR"),
    SMapVal(284, "ESCAPE_SEQUENCE"),
    SMapVal(285, "CC_START"),
    SMapVal(286, "CC_NEGATED"),
    SMapVal(287, "PREDEFINED_CLASS"),
    SMapVal(288, "ORNL"),
    SMapVal(289, "CHAR"),
    SMapVal(290, "CC_PLUS"),
    SMapVal(291, "CC_MINUS"),
    SMapVal(306, "input"),
    SMapVal(307, "opt_directives"),
    SMapVal(308, "section_delimiter"),
    SMapVal(309, "rules"),
    SMapVal(310, "identifier"),
    SMapVal(311, "_sc_name"),
    SMapVal(312, "_start_condition_type"),
    SMapVal(313, "_start_condition_names"),
    SMapVal(314, "_start_condition_directive"),
    SMapVal(315, "_name_def"),
    SMapVal(316, "_name_definition"),
    SMapVal(317, "_directive"),
    SMapVal(318, "option"),
    SMapVal(319, "_directive_line"),
    SMapVal(320, "_baseclassheader"),
    SMapVal(321, "_classheader"),
    SMapVal(322, "_classname"),
    SMapVal(323, "_filenames"),
    SMapVal(324, "_implementationheader"),
    SMapVal(325, "_inputinterface"),
    SMapVal(326, "_inputimplementation"),
    SMapVal(327, "_lexfunctionname"),
    SMapVal(328, "_lexsource"),
    SMapVal(329, "_namespace"),
    SMapVal(330, "_skeleton_directory"),
    SMapVal(331, "_target_directory"),
    SMapVal(332, "_stringOrIdent"),
    SMapVal(333, "_opt_is"),
    SMapVal(334, "combi_chars"),
    SMapVal(335, "_ms_name"),
    SMapVal(336, "_ms_name_list"),
    SMapVal(337, "_ms_specs"),
    SMapVal(338, "_ms_angular"),
    SMapVal(339, "ms_spec"),
    SMapVal(340, "reset"),
    SMapVal(341, "_m_contents"),
    SMapVal(342, "_cc_start"),
    SMapVal(343, "_cc_negated"),
    SMapVal(344, "_cc_end"),
    SMapVal(345, "_cc_literal"),
    SMapVal(346, "_cc_escape"),
    SMapVal(347, "_cc_element"),
    SMapVal(348, "_cc_contents"),
    SMapVal(349, "_cc_set"),
    SMapVal(350, "characterclass"),
    SMapVal(351, "_decimal"),
    SMapVal(352, "_interval"),
    SMapVal(353, "_single_char"),
    SMapVal(354, "_open_paren"),
    SMapVal(355, "_close_paren"),
    SMapVal(356, "_open_curly"),
    SMapVal(357, "_unit"),
    SMapVal(358, "_quantifier"),
    SMapVal(359, "_regex"),
    SMapVal(360, "regexOrEOF"),
    SMapVal(361, "action"),
    SMapVal(362, "_msCompound_regex_list"),
    SMapVal(363, "_msCompound_rule"),
    SMapVal(364, "_msCompound_nl_rule"),
    SMapVal(365, "_opt_msCompound_nl_rules"),
    SMapVal(366, "msCompound"),
    SMapVal(367, "_optMs_regex"),
    SMapVal(368, "_optMs_rule"),
    SMapVal(369, "optMs_rule"),
    SMapVal(370, "_rule_def"),
    SMapVal(371, "_rule"),
    SMapVal(372, "input_$"),
};

SMap s_symbol
(
    s_symArr, s_symArr + sizeof(s_symArr) / sizeof(SMapVal)
);

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(true),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}

// $insert debugfunctions

std::ostringstream ParserBase::s_out__;

std::ostream &ParserBase::dflush__(std::ostream &out)
{
    std::ostringstream &s_out__ = dynamic_cast<std::ostringstream &>(out);

    std::cout << "    " << s_out__.str() << std::flush;
    s_out__.clear();
    s_out__.str("");
    return out;
}

std::string ParserBase::stype__(char const *pre, STYPE__ const &semVal, char const *post) const
{
    return "";
}
std::string ParserBase::symbol__(int value) const
{
    using namespace std;
    ostringstream ostr;
    SMap::const_iterator it = s_symbol.find(value);
    if (it != s_symbol.end())
        ostr << "`" << it->second << "'";
    else if (isprint(value))
        ostr << "`" << static_cast<char>(value) << "' (" << value << ")";
    else
        ostr << "'\\x" << setfill('0') << hex << setw(2) << value << "'";
    return ostr.str();
}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert debug
    if (d_debug__)
        s_out__ <<   "push(state " << state << stype__(", semantic TOS = ", d_val__, ")") << ')' << "\n" << dflush__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    // $insert debug
    if (d_debug__)
        s_out__ <<  "pop(" << count << ") from stack having size " << (d_stackIdx__ + 1) << "\n" << dflush__;
    if (d_stackIdx__ < static_cast<int>(count))
    {
        // $insert debug
        if (d_debug__)
            s_out__ <<  "Terminating parse(): unrecoverable input error at token " << symbol__(d_token__) << "\n" << dflush__;
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert debug
    if (d_debug__)
        s_out__ <<  "pop(): next state: " << d_state__ << ", token: " << symbol__(d_token__) ;
    // $insert debug
    if (d_debug__)
        s_out__ <<  stype__("semantic: ", d_val__) << "\n" << dflush__;
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    // $insert debug
    if (d_debug__)
        s_out__ <<  "executeAction(): of rule " << production ;
    // $insert debug
    if (d_debug__)
        s_out__ <<   stype__(", semantic [TOS]: ", d_val__) << " ..." << "\n" << dflush__;
    switch (production)
    {
        // $insert actioncases
        
        case 2:
#line 83 "grammar"
        {
         d_rules.useInitialSC();
         reset();
         }
        break;

        case 3:
#line 91 "grammar"
        {
         d_val__.get<Tag__::STRING>() = d_matched;
         }
        break;

        case 4:
#line 2 "inc/directives"
        {
         d_expect = "list of start condition names";
         }
        break;

        case 5:
#line 10 "inc/directives"
        {
         d_rules.setType(StartConditions::INCLUSIVE);
         }
        break;

        case 6:
#line 16 "inc/directives"
        {
         d_rules.setType(StartConditions::EXCLUSIVE);
         }
        break;

        case 7:
#line 23 "inc/directives"
        {
         d_rules.addStartCondition(d_vsp__[0].data<Tag__::STRING>());
         }
        break;

        case 8:
#line 28 "inc/directives"
        {
         d_rules.addStartCondition(d_vsp__[0].data<Tag__::STRING>());
         }
        break;

        case 10:
#line 40 "inc/directives"
        {
         d_scanner.newDefinition(); 
         }
        break;

        case 11:
#line 47 "inc/directives"
        {
         d_scanner.addDefinition(d_vsp__[-1].data<Tag__::STRING>(), d_scanner.matched());
         }
        break;

        case 20:
#line 3 "inc/options"
        {
         d_expect = "scanner base class header file name";
         }
        break;

        case 21:
#line 10 "inc/options"
        {
         d_expect = "scanner class header file name";
         }
        break;

        case 22:
#line 17 "inc/options"
        {
         d_expect = "class name";
         }
        break;

        case 23:
#line 24 "inc/options"
        {
         d_expect = "generic filenames specification";
         }
        break;

        case 24:
#line 31 "inc/options"
        {
         d_expect = "implementation header file name";
         }
        break;

        case 25:
#line 38 "inc/options"
        {
         d_expect = "name of the file holding Input's interface";
         }
        break;

        case 26:
#line 45 "inc/options"
        {
         d_expect = "name of the file holding Input's implementations";
         }
        break;

        case 27:
#line 52 "inc/options"
        {
         d_expect = "name of the lex() function";
         }
        break;

        case 28:
#line 59 "inc/options"
        {
         d_expect = "source file name of the lex function";
         }
        break;

        case 29:
#line 66 "inc/options"
        {
         d_expect = "name of the namespace to use";
         }
        break;

        case 30:
#line 73 "inc/options"
        {
         d_expect = "directory name of the flexc++ skeleton files";
         }
        break;

        case 31:
#line 80 "inc/options"
        {
         d_expect = "target directory name for generated files";
         }
        break;

        case 36:
#line 99 "inc/options"
        {
         d_options.setInputInterfacePath(d_matched);
         }
        break;

        case 37:
#line 104 "inc/options"
        {
         d_options.setInputImplementationPath(d_matched);
         }
        break;

        case 38:
#line 109 "inc/options"
        {
         d_options.setClassName(d_matched);
         }
        break;

        case 39:
#line 114 "inc/options"
        {
         d_options.setFilenames(d_matched);
         }
        break;

        case 40:
#line 119 "inc/options"
        {
         d_options.setLexFunctionName(d_matched);
         }
        break;

        case 41:
#line 124 "inc/options"
        {
         d_options.setBaseClassHeaderPath(d_matched);
         }
        break;

        case 42:
#line 129 "inc/options"
        {
         d_options.setClassHeaderPath(d_matched);
         }
        break;

        case 43:
#line 134 "inc/options"
        {
         d_options.setImplementationHeaderPath(d_matched);
         }
        break;

        case 44:
#line 139 "inc/options"
        {
         d_options.setLexSourcePath(d_matched);
         }
        break;

        case 45:
#line 144 "inc/options"
        {
         d_options.setSkeletonDirectory(d_matched);
         }
        break;

        case 46:
#line 149 "inc/options"
        {
         d_options.setTargetDirectory(d_matched);
         }
        break;

        case 47:
#line 154 "inc/options"
        {
         d_options.setNameSpace(d_matched);
         }
        break;

        case 48:
#line 159 "inc/options"
        {
         d_options.setCaseInsensitive();
         }
        break;

        case 49:
#line 164 "inc/options"
        {
         d_options.setInteractive();
         }
        break;

        case 50:
#line 169 "inc/options"
        {
         d_options.setPrint();
         }
        break;

        case 51:
#line 174 "inc/options"
        {
         d_options.setLines(false);
         }
        break;

        case 52:
#line 179 "inc/options"
        {
         d_options.setDebug();
         }
        break;

        case 57:
#line 3 "inc/msspec"
        {
         d_rules.activateStartCondition(d_vsp__[0].data<Tag__::STRING>());
         }
        break;

        case 60:
#line 16 "inc/msspec"
        { 
         d_rules.useAll();
         }
        break;

        case 62:
#line 25 "inc/msspec"
        {
         d_scanner.acceptMulti();
         }
        break;

        case 64:
#line 2 "inc/characterclass"
        {
         d_expect = "character class";
         }
        break;

        case 65:
#line 10 "inc/characterclass"
        {
         d_val__.get<Tag__::CHARCLASS>() = CharClass::elements(d_matched, 1); 
         }
        break;

        case 66:
#line 18 "inc/characterclass"
        { 
         d_val__.get<Tag__::CHARCLASS>() = CharClass::elements(d_matched, 2); 
         }
        break;

        case 67:
#line 25 "inc/characterclass"
        {
         d_expect = "pattern or action block";
         }
        break;

        case 91:
#line 83 "inc/characterclass"
        {
         d_val__.get<Tag__::CHARCLASS>() = CharClass::escape(d_matched);
         }
        break;

        case 92:
#line 88 "inc/characterclass"
        {
         d_val__.get<Tag__::CHARCLASS>() = CharClass::predefined(d_matched);
         }
        break;

        case 93:
#line 93 "inc/characterclass"
        {
         d_val__.get<Tag__::CHARCLASS>() = CharClass::elements(d_matched, 0);
         }
        break;

        case 94:
#line 100 "inc/characterclass"
        {
         d_vsp__[-1].data<Tag__::CHARCLASS>().concatenate(d_vsp__[0].data<Tag__::CHARCLASS>());
         }
        break;

        case 97:
#line 111 "inc/characterclass"
        {
         d_vsp__[-1].data<Tag__::CHARCLASS>().negate();
         }
        break;

        case 98:
#line 116 "inc/characterclass"
        {
         d_vsp__[-2].data<Tag__::CHARCLASS>().concatenate(d_vsp__[-1].data<Tag__::CHARCLASS>());
         }
        break;

        case 99:
#line 121 "inc/characterclass"
        {
         d_val__.get<Tag__::CHARCLASS>() = d_vsp__[-2].data<Tag__::CHARCLASS>().negate(d_vsp__[-1].data<Tag__::CHARCLASS>());
         }
        break;

        case 100:
#line 128 "inc/characterclass"
        {
         d_val__.get<Tag__::CHARCLASS>() = CharClass::unite(d_vsp__[-2].data<Tag__::CHARCLASS>(), d_vsp__[0].data<Tag__::CHARCLASS>());
         }
        break;

        case 101:
#line 133 "inc/characterclass"
        {
         d_val__.get<Tag__::CHARCLASS>() = CharClass::difference(d_vsp__[-2].data<Tag__::CHARCLASS>(), d_vsp__[0].data<Tag__::CHARCLASS>());
         }
        break;

        case 103:
#line 3 "inc/regexoreof"
        {
         d_val__.get<Tag__::STRING>() = d_matched;
         }
        break;

        case 104:
#line 10 "inc/regexoreof"
        {
         d_val__.get<Tag__::INTERVAL>() = Interval::exact(d_vsp__[0].data<Tag__::STRING>());
         }
        break;

        case 105:
#line 15 "inc/regexoreof"
        {
         d_val__.get<Tag__::INTERVAL>() = Interval::range(d_vsp__[-2].data<Tag__::STRING>(), d_vsp__[0].data<Tag__::STRING>());
         }
        break;

        case 106:
#line 20 "inc/regexoreof"
        {
         d_val__.get<Tag__::INTERVAL>() = Interval::lowerBound(d_vsp__[-1].data<Tag__::STRING>());
         }
        break;

        case 109:
#line 33 "inc/regexoreof"
        {
         ++d_parentheses;
         }
        break;

        case 110:
#line 40 "inc/regexoreof"
        {
         --d_parentheses;
         }
        break;

        case 111:
#line 47 "inc/regexoreof"
        {
         d_scanner.acceptMulti();
         }
        break;

        case 112:
#line 54 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = boln();
         }
        break;

        case 113:
#line 59 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = dollar();
         }
        break;

        case 114:
#line 64 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = eolnDollar();
         }
        break;

        case 115:
#line 69 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = str();
         }
        break;

        case 116:
#line 74 "inc/regexoreof"
        { 
         d_val__.get<Tag__::PATTERN>() = quotes();
         }
        break;

        case 117:
#line 79 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = escape();
         }
        break;

        case 118:
#line 84 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = Pattern::dot(d_states);
         }
        break;

        case 119:
#line 89 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = rawText();
         }
        break;

        case 120:
#line 94 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = Pattern::characterClass(d_states, d_vsp__[0].data<Tag__::CHARCLASS>());
         }
        break;

        case 124:
#line 114 "inc/regexoreof"
        {
         Options::regexCall("unit");
         }
        break;

        case 125:
#line 119 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = interval(d_vsp__[-3].data<Tag__::PATTERN>(), d_vsp__[-1].data<Tag__::INTERVAL>());
         }
        break;

        case 126:
#line 124 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = Pattern::quantifier(d_states, d_vsp__[-1].data<Tag__::PATTERN>(), d_matched[0]);
         }
        break;

        case 127:
#line 129 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = d_vsp__[-1].data<Tag__::PATTERN>();
         }
        break;

        case 128:
#line 134 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = Pattern::concatenate(d_states, d_vsp__[-1].data<Tag__::PATTERN>(), d_vsp__[0].data<Tag__::PATTERN>());
         }
        break;

        case 129:
#line 139 "inc/regexoreof"
        { 
         d_val__.get<Tag__::PATTERN>() = Pattern::alternatives(d_states, d_vsp__[-2].data<Tag__::PATTERN>(), d_vsp__[0].data<Tag__::PATTERN>());
         }
        break;

        case 130:
#line 144 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = lookahead(d_vsp__[-2].data<Tag__::PATTERN>(), d_vsp__[0].data<Tag__::PATTERN>());
         }
        break;

        case 132:
#line 153 "inc/regexoreof"
        {
         d_val__.get<Tag__::PATTERN>() = Pattern::eof(d_states);
         }
        break;

        case 133:
#line 6 "inc/action"
        {
         block(); 
         }
        break;

        case 134:
#line 2 "inc/reset"
        {
         reset();
         }
        break;

        case 135:
#line 5 "inc/mscompound"
        {
         orAction();
         }
        break;

        case 136:
#line 10 "inc/mscompound"
        {
         addRule(d_vsp__[0].data<Tag__::PATTERN>());
         }
        break;

        case 138:
#line 21 "inc/mscompound"
        {
         noActions();
         }
        break;

        case 139:
#line 26 "inc/mscompound"
        {
         assignBlock();
         }
        break;

        case 143:
#line 43 "inc/mscompound"
        { 
         d_rules.resetStartConditions();
         }
        break;

        case 144:
#line 4 "inc/optmsrule"
        {
         d_val__.get<Tag__::PATTERN>() = d_vsp__[0].data<Tag__::PATTERN>();
         }
        break;

        case 146:
#line 20 "inc/optmsrule"
        {
         orAction();
         }
        break;

        case 147:
#line 25 "inc/optmsrule"
        {
         addRule(d_vsp__[0].data<Tag__::PATTERN>(), true); 
         }
        break;

        case 149:
#line 37 "inc/optmsrule"
        {
         assignBlock();
         }
        break;

    }
    // $insert debug
    if (d_debug__)
        s_out__ <<  "... action of rule " << production << " completed" ;
    // $insert debug
    if (d_debug__)
        s_out__ <<   stype__(", semantic: ", d_val__) << "\n" << dflush__;
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

    // $insert debug
    if (d_debug__)
        s_out__ <<  "reduce(): by rule " << (&pi - s_productionInfo) ;
    // $insert debug
    if (d_debug__)
        s_out__ <<  " to N-terminal " << symbol__(d_token__) << stype__(", semantic = ", d_val__) << "\n" << dflush__;
}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
        // $insert debug
        if (d_debug__)
            s_out__ <<  "nextToken(): popped " << symbol__(d_token__) << stype__(", semantic = ", d_val__) << "\n" << dflush__;
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
    // $insert debug
    if (d_debug__)
        s_out__ <<  "nextToken(): using " << symbol__(d_token__) << stype__(", semantic = ", d_val__) << "\n" << dflush__;
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
        // $insert debug
        if (d_debug__)
            s_out__ <<  "lookup(" << d_state__ << ", " << symbol__(d_token__) ;
        // $insert debug
        if (d_debug__)
            s_out__ <<  "): default reduction by rule " << -elementPtr->d_action << "\n" << dflush__;
            return elementPtr->d_action;                
        }
        // $insert debug
        if (d_debug__)
            s_out__ <<  "lookup(" << d_state__ << ", " << symbol__(d_token__) << "): Not " ;
        // $insert debug
        if (d_debug__)
            s_out__ <<  "found. " << (recovery ? "Continue" : "Start") << " error recovery."  << "\n" << dflush__;

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;

// $insert debuglookup
    if (d_debug__)
    {
        s_out__ <<  "lookup(" << d_state__ << ", " << symbol__(d_token__);

        if (action < 0)             // a reduction is found
            s_out__ << "): reduce by rule " << -action;
        else if (action == 0)
            s_out__ <<  "): ACCEPT";
        else 
            s_out__ <<  "): shift " << action << " (" << symbol__(d_token__) << 
                        " processed)";

        s_out__ << "\n" << dflush__;
    }

    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }

    // $insert debug
    if (d_debug__)
        s_out__ <<  "errorRecovery(): " << d_nErrors__ << " error(s) so far. State = " << top__() << "\n" << dflush__;

    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        // $insert debug
        if (d_debug__)
            s_out__ <<  "errorRecovery(): pop state " << top__() << "\n" << dflush__;
        pop__();
    }
    // $insert debug
    if (d_debug__)
        s_out__ <<  "errorRecovery(): state " << top__() << " is an ERROR state" << "\n" << dflush__;

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();
                // $insert debug
                if (d_debug__)
                    s_out__ <<  "errorRecovery() SHIFT state " << action ;
                // $insert debug
                if (d_debug__)
                    s_out__ <<  ", continue with " << symbol__(d_token__) << "\n" << dflush__;

                if (gotToken)
                {
                    // $insert debug
                    if (d_debug__)
                        s_out__ <<  "errorRecovery() COMPLETED: next state " ;
                    // $insert debug
                    if (d_debug__)
                        s_out__ <<  action << ", no token yet" << "\n" << dflush__;

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
                // $insert debug
                if (d_debug__)
                    s_out__ <<  "errorRecovery() REDUCE by rule " << -action ;
                // $insert debug
                if (d_debug__)
                    s_out__ <<  ", token = " << symbol__(d_token__) << "\n" << dflush__;
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    // $insert debug
    if (d_debug__)
        s_out__ <<  "parse(): Parsing starts" << "\n" << dflush__;
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        // $insert debug
        if (d_debug__)
            s_out__ <<  "==" << "\n" << dflush__;
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    // $insert debug
    if (d_debug__)
        s_out__ <<  "parse(): returns " << retValue << "\n" << dflush__;
    return retValue;
}

// $insert polymorphicImpl
namespace Meta__
{
   Base::~Base()
   {}
}




