// Generated by Bisonc++ V2.7.0 on Wed, 31 Mar 2010 12:18:29 +0200

#ifndef Parser_h_included
#define Parser_h_included

#include <vector>

#include "../state/state.h"

// $insert baseclass
#include "parserbase.h"
// $insert scanner.h
#include "../scanner/scanner.h"

namespace FBB
{
    class Arg;
}

class Options;
class States;
class Rules;

#undef Parser
class Parser: public ParserBase
{
    typedef Scanner::StartCondition__ StartCondition__;

    FBB::Arg &d_arg;

    // $insert scannerobject
    Scanner d_scanner;

    Options &d_options;
    std::string d_msg;
    bool d_printTokens;
    size_t d_parentheses;

    bool d_usesLOP;
    bool d_BOLpattern;              // true for patterns starting at BOL

    size_t d_patternTokenCount;
    bool d_doError;                 // use the error() function at ERRORs

    Rules &d_rules;
    States &d_states;

    static int s_ignoreToken;
    static std::string s_lastMsg;


    public:
        Parser(Rules &rules, States &states);
        int parse();

    private:

        void setFlags(size_t idx, State::Flag flag);    // called fm lookahead

//        std::ostream &lineMsg(int deltaLineNo) const;
        void modePattern();
        void sectionDelimiter();

        spSemVal interval(SemVal &low, SemVal &high);
        spSemVal lookahead(SemVal &left, SemVal &right);
        spSemVal eofPattern();

        void warnForSpecialChars() const;
        void error(char const *msg);    // called on (syntax) errors
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc

    // support functions for parse():
        void executeAction(int ruleNr);
        void errorRecovery();
        int lookup(bool recovery);
        void nextToken();
};


#endif
