#!/bin/bash

OLD=ih
NEW=hh

case $1 in
    (dry)
        for x in `find -name "*.${OLD}"`
        do
            echo mv $x ${x%${OLD}}${NEW}
        done

        for x in `find -name "*.cc"`
        do
            GREP=`grep '.*#include\s\+"[^.]\+\.'${OLD}'"' < $x`
            OK=$?

            [ $OK -eq 0 ] || continue

            echo "$x: ${GREP}->"\
`echo $GREP | sed '
s/\(.*#include\s\+"[^.]\+\.\)'${OLD}'\(.*\)/\1'${NEW}'\2/
'`
        done
    ;;

     (run)
        for x in `find -name "*.${OLD}"`
        do
            echo mv $x ${x%${OLD}}${NEW}
            mv $x ${x%${OLD}}${NEW}
        done

        for x in `find -name "*.cc"`
        do
            GREP=`grep '.*#include\s\+"[^.]\+\.'${OLD}'"' < $x`
            OK=$?

            [ $OK -eq 0 ] || continue

            echo "$x: ${GREP}->"\
`echo $GREP | sed '
s/\(.*#include\s\+"[^.]\+\.\)'${OLD}'\(.*\)/\1'${NEW}'\2/
'`

            sed -i '
s/\(.*#include\s\+"[^.]\+\.\)'${OLD}'\(.*\)/\1'${NEW}'\2/
' $x
        done
     ;;

     (git)
        for x in `find -name "*.${OLD}"`
        do
            echo mv $x ${x%${OLD}}${NEW}
            git mv -f $x ${x%${OLD}}${NEW}
        done

        for x in `find -name "*.cc"`
        do
            GREP=`grep '.*#include\s\+"[^.]\+\.'${OLD}'"' < $x`
            OK=$?

            [ $OK -eq 0 ] || continue

            echo "$x: ${GREP}->"\
`echo $GREP | sed '
s/\(.*#include\s\+"[^.]\+\.\)'${OLD}'\(.*\)/\1'${NEW}'\2/
'`

            sed -i '
s/\(.*#include\s\+"[^.]\+\.\)'${OLD}'\(.*\)/\1'${NEW}'\2/
' $x
        done
     ;;

    (*)
    echo "
Usage: $0 dry|run|git
    This script converts the .${NEW} headers in and below the current working
    directory to .${OLD} files, and changes \`#include \"xxx.${NEW}\"' in .cc files 
    into \`#include \"xxx.${OLD}\"' directives.
Arguments:    
    dry: show the commands that are executed with \`$0 run\'
    run: perform the conversions
    git: same as run, but does 'git mv -f ...' instead of 'mv ...'
"
    ;;
esac
    
