// Generated by Flexc++ v0.7.0~pre on Tue, 23 Mar 2010 10:01:46 +0000

#ifndef SCANNER_H_INCLUDED_
#define SCANNER_H_INCLUDED_

#include <string>
#include <stack>
#include <unordered_map>

#include "../block/block.h"

#include <iosfwd>
#include "scannerbase.h"

// $insert namespace-open

class SemVal;

class Scanner: public ScannerBase
{
    Block   d_block;
    std::string d_filename;
    std::stack<StartCondition> d_fromCondition;

    std::unordered_map<std::string, std::string> d_nameExpansion;
    std::string d_patternName;
    bool d_beginOfPattern;
    bool d_initialClosingBracket;

    public:
        Scanner(std::string const &fname);

        int lex();
        int pLex();     // calls/returns lex(), clears beginOfPattern

        std::string const &filename() const;
        void addDefinition(SemVal const &name, SemVal const &definition);
        void newDefinition();
        void reset(StartCondition start);
        void undelimit();
        std::ostream &lineMsg(int deltaLineNo = 0) const;
        std::string const &block() const;

    private:
        void begin(StartCondition to);
        int begin(StartCondition to, int token);
        int end(int token = -1);    // go back to pushed startcondition
                                    // (if any) return token. 

        void pushNameExpansion();
        void pushEOLNlookahead();
        void maybeSwitchStream();

        int executeAction(int ruleNr);
        int lex__();
        int executeAction__(int ruleNr);
};

inline std::string const &Scanner::filename() const
{
    return d_filename;
}

inline void Scanner::newDefinition()
{
    d_patternName.clear();
}

inline std::string const &Scanner::block() const
{
    return d_block.str();
}

inline int Scanner::lex()
{
    return lex__();
}

// $insert namespace-close


#endif // SCANNER_H_INCLUDED_
